### ISSUE TITLE
Not working in XCode 7.1.1

### ISSUE THREAD

**Issue by streamtree** [Jintin/Swimat#1]
I installed into XCode 7.1.1 using Alcatraz but the Swimat option does not appear in the Edit menu.

**Comment by Jintin** [comment]
Would you please build it directly now.
Seems like Alcatraz don't support workspace to build.
I'll try to find other solution soon,
Thank you for report the bug.

**Comment by marecektn** [comment]
I build it with pod install and it does not appear in XCode
XCode ver: 7.1.1

Anyway, thanks for your time and effort!

**Comment by Jintin** [comment]
Try if build and restart work?
If don't, feel free to let me know. 
You're welcome. ^^

**Comment by marecektn** [comment]
several builds and restarts later.. it works :) 
It's nice!

**Comment by Jintin** [comment]
I change the workspace to a single project.
The Alcatraz plugin is active right now.
Thank you all for report.
