### ISSUE TITLE
Custom operators support

### ISSUE THREAD

**Issue by olferuk** [Jintin/Swimat#100]
It would be great if Swimat could analyze the global operators defined in the file and won't affect them in the next occurrences.
For example, now Swimat corrects operator like `>--` to be `> --`, and extra space obviously leaves an error.

**Comment by Jintin** [comment]
Yes, it a problem.
Since we don't actually parse code, so don't get the custom operators.
Is >-- from any library or you define yourself?

**Comment by Jintin** [comment]
If it from other library then we can add new rule since other people might face the same problem.
If you define your own, I can help you build your own Swimat for workaround.
To be solid solve this, we'll support external rule file in the future.
Thank you for your feedback.

**Comment by olferuk** [comment]
@Jintin I encountered the same problem either in the other libraries and in my own code. 
Take a look at this one: https://github.com/antitypical/Result , it defines it's own operators in `ResultType.swift`.
However, Runes operators (https://github.com/thoughtbot/Runes) do not suffer from the formatting problem, luckily their operators are combined with right combinations of symbols 😃

**Comment by Jintin** [comment]
Yes, runes is added in the rule file.
If you want to support operator yourself, you can fork Swimat and change it.
1. open `Swimat/SwiftParser.m` file
2. find `checkOperator:` function
3. find corresponding case and add your operator.

For example, I want to add `++++` operator.
in SwiftParser.m line 377, change 
`NSArray *array = @[@"+++=", @"+++", @"+=<", @"+="];` 
to 
`NSArray *array = @[@"++++", @"+++=", @"+++", @"+=<", @"+="];` 
will do the job.

After editing you can run it to testing, if everything work you can just build and reopen Xcode.
Then you have your own version of Swimat.
And if you find any operator is well known, you can send pull request as well.

Tell me if you have any problem. ^^

**Comment by olferuk** [comment]
Ok, I'll give it a try.
Also, I think you can surely add to the master branch any support of any operators mixed with `--` and `++` symbols, as far as increments/decrements are deprecated now: https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md .

**Comment by Jintin** [comment]
I'll close it right now, you can reopen or create new issue if you found other operator should added. 
Thank you.
