### ISSUE TITLE
Negative number in an array broken

### ISSUE THREAD

**Issue by iamszabo** [Jintin/Swimat#101]
If you have a negative number in an array swimat inserts a space between the sign and the number.
`[-1]` results with `[ - 1]` that pops up with a warning `Unary operator cannot be separated from its operand`

**Comment by Jintin** [comment]
Thank you for your feedback.
Please reinstall and try again.

**Comment by iamszabo** [comment]
Thank you for the quick fix. Keep up the good work ;)

**Comment by Jintin** [comment]
You're welcome. :)
