### ISSUE TITLE
Empty line cause incorrect indentation

### ISSUE THREAD

**Issue by jsaguiar** [Jintin/Swimat#102]
``` swift
         if string.isEmpty {

            return nil
        }

```

formats to

``` swift
         if string.isEmpty {

return nil
        }

```

**Comment by Jintin** [comment]
Hi, please update and try again.
It might be fix in previous release.

**Comment by jsaguiar** [comment]
I continue to have the same issue
Try this: 

``` swift
    func functionName() {

        print("string")
    }
```

**Comment by Jintin** [comment]
Yes I tried.
But not thing change.
Can you reopen Xcode or let me know your setting.
like this:
<img width="394" alt="screen shot 2016-05-05 at 8 06 34 pm" src="https://cloud.githubusercontent.com/assets/3413874/15043167/ed7d8b4e-12fc-11e6-8e40-fb5d33e9dd69.png">

**Comment by jsaguiar** [comment]
What is causing the bug is the "Indent Empty Line" setting

**Comment by Jintin** [comment]
Thank your for your feedback.
I think it work now.
