### ISSUE TITLE
Problem with range operators

### ISSUE THREAD

**Issue by GabrielCartier** [Jintin/Swimat#103]
Swimat seems to have problems handling range operators.

This:

``` swift
for index in 0...1 {            
}
```

Will get formatted to:

``` swift
for index in 0 ... 1 {            
}
```

Although the syntax is correct, I feel like it doesn't follow the Swift standard. No where in Apple documentation will they use the syntax with space.

Let me know if that makes sense.

**Comment by Jintin** [comment]
I've seen both case, and decide space is a more elegant way.
But you're right, maybe it's better to let people choose which format they like.
So current version both format will be valid.
Thank you for your feedback.
