### ISSUE TITLE
Guard statment else not indented

### ISSUE THREAD

**Issue by dejanskledar** [Jintin/Swimat#104]
I just noticed that the `guard else` statement isn't indented currently.

Heres the **Xcode default** indentation:

```
let some: NSError?

guard let _some = some
    else {
        //        
}
```

And the **Swimat** indentation:

```
let some: NSError?

guard let _some = some
else {
    //
}
```

**Comment by Jintin** [comment]
Thank you for your feedback, please give me a couple days to find out how to fix.

**Comment by Jintin** [comment]
Can you try our swift version.
https://github.com/Jintin/Swimat/tree/swift
Clone, build and restart Xcode.
If you encounter any problem, please feel free to let me know.
Thank you.

**Comment by dejanskledar** [comment]
Perfect! Works like a charm!

**Comment by Jintin** [comment]
You're welcome.
