### ISSUE TITLE
Issue with variadoc operator

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#105]
See below:

Before Save

![screen shot 2016-05-19 at 2 19 03 pm](https://cloud.githubusercontent.com/assets/3022693/15404695/b976551c-1dcc-11e6-8dc5-83aa11ac5e19.png)

After Save

![screen shot 2016-05-19 at 2 19 12 pm](https://cloud.githubusercontent.com/assets/3022693/15404696/b977986e-1dcc-11e6-870c-3c0467cc975f.png)

**Comment by Jintin** [comment]
Thank you for your reporting.
Can you give me the plain text?
Wrap in  ``` block will perform a code style.

**Comment by Jintin** [comment]
Thank you for your feedback, it should work right now.
But you have to adjust to correct version first. ^^"
