### ISSUE TITLE
Auto formatting inside the content of documentation

### ISSUE THREAD

**Issue by nullm4ri** [Jintin/Swimat#106]
I think this is similar question with #70 .
There is document about [markup for swift symbols](https://developer.apple.com/library/mac/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497-CH2-SW1)

I want to use that markup but Swimat doing code reformat inside /*\* this block */
Can you fix this?

**Comment by Jintin** [comment]
```
/*!
 * @brief The car will drive, and then execute the drive block
 * @param completion A driveCompletion block
 * @code [car driveCarWithCompletion:^(CGFloat distance){
 *  NSLog(@"Distance driven %f", distance);
 * }];
 */
```

Is this sample work?
Swimat only add space before `*`.
Can you give me some not working sample.
Thank you for your feedback.
Document is quite important that we need supported.

**Comment by nullm4ri** [comment]
I wrote comment like below - without `*`.

```
/**
  @brief The car will drive, and then execute the drive block
  @param completion A driveCompletion block
  @code [car driveCarWithCompletion:^(CGFloat distance){
   NSLog(@"Distance driven %f", distance);
  }];
 */
```

I added `*` before space at each line just like your example, and it works WELL!
Thank you for your kindness 👍

**Comment by Jintin** [comment]
You're welcome. ^^
