### ISSUE TITLE
Issue with formatting contents inside of ternary operator

### ISSUE THREAD

**Issue by olferuk** [Jintin/Swimat#107]
Hey there
I found yet another bug working with Swimat.
See:

``` objc
let condition = true
let delegateA: (()->())? = { print("A") }
let delegateB: (()->())? = { print("B") }
condition ? delegateA?() : delegateB?()
```

After swimat formatting, it leaves it like so:

``` objc
condition ? delegateA ? () : delegateB?()
//added extra spaces,^ ^ so it produces a compilation error
```

I guess, Swimat considered second `?` as a part of the ternary operator?..

**Comment by Jintin** [comment]
Yes, it a bug.
I'll try my best to fix it.
And it seems work in our swift version.
You can clone https://github.com/Jintin/Swimat/tree/swift and build it yourself first. 
Thank you for your feedback.

**Comment by Jintin** [comment]
Is this ok for you?

**Comment by Jintin** [comment]
It's work both in `swift` & `extension` branch.
So I'll close it now.
You can open it again or fire another issue if you have any problem.
