### ISSUE TITLE
Lining up parameters in method calls

### ISSUE THREAD

**Issue by adamlehde** [Jintin/Swimat#108]
In a Swift file in Xcode, find a method with multiple params.  Hit Enter for a new line after every comma to line up params vertically.   Hit Command+a, Ctrl+i.  This will line up the beginning of every parameter name in a method call.  Then hitting save with SwimAt enabled will mess that up and push everything to the left.
 (correct format shown below) 
![screen shot 2016-06-01 at 10 36 26 am](https://cloud.githubusercontent.com/assets/6911424/15715624/c41b1954-27e4-11e6-8071-ce05b8ae4d0f.png)

**Comment by Jintin** [comment]
Would you please try our swift version?
I've add this feature today.
https://github.com/Jintin/Swimat/tree/swift
Clone, build and restart Xcode.
If you encounter any problem, please feel free to let me know.
Thank you.

**Comment by Jintin** [comment]
also same as #82
