### ISSUE TITLE
Swimat breaks string literals

### ISSUE THREAD

**Issue by pteasima** [Jintin/Swimat#109]
The minimal code to reproduce this issue is:

```
"
"Hello/playground"
```

When you format this code, spaces are inserted around the '/' resulting in:

```
"
"Hello / playground"
```

Obviously this code isnt valid, but you can change it later to some valid code and the string literal keeps the spaces. Swift's string literal should end on newline, so this definitely shouldnt be happening. I encourage everyone to stop using swimat until this is resolved. Ive had two ugly regression bugs in the past week because swimat messed up some url string literal in parts of the file I didnt even touch.

**Comment by Jintin** [comment]
Thanks for your feedback.
Swimat is bound with "undo" function, so if you found compile error like your example I suggest you to do undo.

One solution is if the code syntax is not correct show error notification and no format.
But it's not common issue so I might fix it later.

**Comment by Jintin** [comment]
Hi, please try the swift version.
Check out the swift branch and build yourself.
Tell me if you found more issue. ^^ 
Thank you.

**Comment by entonio** [comment]
Hi. In my opinion, this is a bug, not an enhancement.

**Comment by pteasima** [comment]
Sorry, closing this was a misclick. @Jintin do you still need me to check your fix? I was inactive the last few weeks :(

**Comment by Jintin** [comment]
@pteasima it's perfect if you can help to verify once more.
@entonio it ok to flag as an issue or enhancement. 
But I think for this case we need to add a feature to check if the format is broken at first.
So I flag it as enhancement.

**Comment by Jintin** [comment]
@pteasima
It will throw format error both `swift` and `extension` branch now so I'll close this issue.
Open it again if you have any question.
