### ISSUE TITLE
Do not remove all blank lines between forEach calls

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#114]
If I have

``` swift
    func viewDidLoad()
    {
        [label1].forEach { label in
            label.configure()
        }
        <blank line here>
        [button1, button2].forEach { button in
            button.configure()
        }
    }
```

Swimat removes the blank line.
I understand if it turns N lines into just 1, or if it completely removed lines at the beginnign and end of code blocks, but a line separating different blocks should be kept.

**Comment by Jintin** [comment]
This is a bug. XD
I'll fix it in following days.
Thank you for your reporting.

**Comment by Jintin** [comment]
Please update and try again.
Thank you.
