### ISSUE TITLE
'Break before opening brace' set to remove does not remove non-newline whitespace

### ISSUE THREAD

**Issue by elainemckinley** [Jintin/Swimat#115]
Let's say I have the following (incorrectly formatted) code:

```
    func foo()
    {
        print("Hello!")
    }
```

After formatting, the spaces that were on the second line are not deleted, only the newline character was. So here's what it ends up looking like after linting:

```
    func foo()    {
        print("Hello!")
    }
```

A simple workaround for now is to simply reformat again, which gets rid of the excess whitespace.

```
    func foo() {
        print("Hello!")
    }
```

A very small issue with an easy workaround, and it's the only problem I've had so far. Overall I'm really happy with this plugin!

**Comment by Jintin** [comment]
Thank you for your report and compliment, please reinstall and try again.

**Comment by elainemckinley** [comment]
👍  Thanks!

**Comment by ghost** [comment]
Hello,
I have tried your plugin and the formatting is so much better!
But I am not a fan of this:

```
func foo()
{
   print("this is sooo ugly!!")
}
```

I would like to have it like this

```
func foo() {
    print("this is so much prettier!")
}
```

Using your plugin does not put the { at the right place as described in the posting above. Am I missing something? In the Settings there is only the possibility to change indentation...

**Comment by saagarjha** [comment]
@Malkavian89 Some people prefer the Allman style, so we've kept it as-is. If you'd like it to look like the latter, you'll have to put the brace on the same line yourself to signal that you'd like the K&R style.

**Comment by ghost** [comment]
@saagarjha Thank you for your response. I wish I could set the K&R style as default... well then, manually editing it is then, I guess.

**Comment by saagarjha** [comment]
@Jintin Maybe we could add an option that forces a particular style?

**Comment by ghost** [comment]
I would really appreciate it! @Jintin 👍🏻
