### ISSUE TITLE
swimat breaks =~ operator

### ISSUE THREAD

**Issue by pteasima** [Jintin/Swimat#116]
`=~` gets separated to `= ~`, which doesnt build.

**Comment by Jintin** [comment]
Does `=~` a third party operator?

**Comment by pteasima** [comment]
yes, I cant remember which library its from, but definitely 3rd party. Anyway, I think its a reasonable operator to use.

Get Outlook for iOS

On Sun, Jul 24, 2016 at 4:26 AM +0200, "Jintin" notifications@github.com wrote:

Does =~ a third party operator?

**Comment by Jintin** [comment]
Would you try to build your own version?
You can copy this repo and modify `SwiftParser.m` line 504 to: 

``` swift
NSArray *array = @[@"===", @"==", @"=~", @"="];
```

**Comment by Jintin** [comment]
And we'll add custom operator support in future version.
Thank you for your report. ^^

**Comment by Jintin** [comment]
#112
