### ISSUE TITLE
Swimat breaks floating point numbers with exponent

### ISSUE THREAD

**Issue by vhailor13** [Jintin/Swimat#117]
Before:  bigRoot = (bigRoot <= **1e-2**) ? 0 : bigRoot;
After:  bigRoot = (bigRoot <= **1e - 2**) ? 0 : bigRoot;

**Comment by Jintin** [comment]
Thank you, but it should be fix in #111 both the master and swift branch.
You can update and try again.
Please let me know if there still other problem.
