### ISSUE TITLE
How I can avoid the Swimat format my documentation blocks

### ISSUE THREAD

**Issue by RafaelPlantard** [Jintin/Swimat#118]
For example I have this desired documentation block:

``` swift
/**
 It will try to start the iShopSDK.

 You can pass in `valueToReturn` parameter the value you want this method returns.
 For example, to use its returns directly in a call:

 $
 func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    return ShopSDK.start(valueToReturn: false)
 }
 $

 - Parameter valueToReturn: The `Bool` value that will be returned for this method.
 - Returns: Always return the `valueToReturn` value, its default value is `True`.
 */
static func start(valueToReturn value: Bool = true) -> Bool {
    sharedInstance.core.login()

    return value
}
```

$ -> ```

But, when I format the code with Swimat, the code block of my documentation block is incorrectly formatted:

``` swift
/**
 It will try to start the iShopSDK.

 You can pass in `valueToReturn` parameter the value you want this method returns.
 For example, to use its returns directly in a call:

 $
 func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
return ShopSDK.start(valueToReturn: false)
 }
 $

 - Parameter valueToReturn: The `Bool` value that will be returned for this method.
 - Returns: Always return the `valueToReturn` value, its default value is `True`.
 */
static func start(valueToReturn value: Bool = true) -> Bool {
    sharedInstance.core.login()

    return value
}
```

There is way of the Swimat recognize the code block inside the documentation block and format it correctly? Or a way to do the Swimat just ignore code blocks format inside a documentation block?

More about Swift Documentation at [here](http://nshipster.com/swift-documentation/)

**Comment by Jintin** [comment]
We can separate non-format and format with `/**   */` and `/* */`.
What do you think?

**Comment by RafaelPlantard** [comment]
It's a good way to solve this problem, but, I would like to maintain the format in `\** */` block, and only disable format when those blocks have inside it a ``` block. What you think? If it's not possible, your solution already helps me a lot.

**Comment by Jintin** [comment]
In the tutorial site you provide, it has some format is not align like below

``` swift
/**
    # Lists

    You can apply *italic*, **bold**, or `code` inline styles.

    ## Unordered Lists

    - Lists are great,
    - but perhaps don't nest
    - Sub-list formatting

      - isn't the best.

    ## Ordered Lists

    1. Ordered lists, too
    2. for things that are sorted;
    3. Arabic numerals
    4. are the only kind supported.
*/
```

So I think it's hard to implement the way you want.

**Comment by RafaelPlantard** [comment]
I agree with you. So, is it possible implement your solution?
See it, also:
![screen shot 2016-08-11 at 15 15 04](https://cloud.githubusercontent.com/assets/5968478/17599641/77969098-5fd6-11e6-9e44-48b590a3d123.png)

**Comment by Jintin** [comment]
Sorry being late.
Please update and try again.
