### ISSUE TITLE
Negative number with a conditionnal operator is broken

### ISSUE THREAD

**Issue by Jems22** [Jintin/Swimat#119]
If you use a negative number within a conditionnal operator swimat inserts a space between the sign and the number.
myVar==1 ? -1 : 0 results with myVar==1 ? - 1 : 0 that pops up with a warning Unary operator cannot be separated from its operand

**Comment by Jintin** [comment]
Thank you for your feedback, please update and try again. ^^

**Comment by Jems22** [comment]
It's ok, it works now.
Thanks for your quick fix.
