### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by cshireman** [Jintin/Swimat#12]
Is it possible to configure the plugin to format the files on save?  It would remove the need to remember to apply the formatting and keep the formatting consistent for an entire project and team without anyone having to think about it.

**Comment by Jintin** [comment]
Sure, it's a good feature and indeed in our roadmap.
We'll add this in later version.
But since there are lots of enhancement request.
It'll take some times. Thank you for sharing your idea about Swimat.
^^

**Comment by Jintin** [comment]
Please try the 1.6 version.
Thank you for give us the advise and Happy New Year. ^^
