### ISSUE TITLE
Issue when formatting numbers inside brackets

### ISSUE THREAD

**Issue by aksdenn** [Jintin/Swimat#120]
Hi,

I think I found a bug on Swimat
When I have something like:

`let object = array[index! - 1]`

When I format, it becomes:

`let object = array[index! -1]`

Creating a compile error

**Comment by Jintin** [comment]
I didn't find any problem.
Would you update and try again.
Maybe it is fix in previous commit.

**Comment by aksdenn** [comment]
Hi, I tried again and it's working perfectly. Thanks!
