### ISSUE TITLE
Xcode crash when install Swimat and JSPatch When Editing JS File

### ISSUE THREAD

**Issue by neonio** [Jintin/Swimat#121]

**Comment by Jintin** [comment]
our plugin only modify *.swift or *.playground files.
How do you produce this problem? only editing? or save? or hit format?

我們的 plugin 只有在 *.swift 或 *.playground 的檔案才會運作
請問你是在什麼樣的操作下造成這個問題呢? 純編輯? 存擋? 按下排版鍵?

**Comment by Jintin** [comment]
do you have any update?

**Comment by Jintin** [comment]
do you have any update?

**Comment by Jintin** [comment]
The information is not sufficient, will maybe out of date.
You can try `extension` for Xcode8 source code extension.
