### ISSUE TITLE
Swift 3?

### ISSUE THREAD

**Issue by awclives** [Jintin/Swimat#124]
Greetings,

How weary, stale, flat, and unprofitable
seem to me all my lines of code
since I upgraded to Swift 3
and now have to format them myself.

To confirm, this plugin does not work for Swift 3, correct?  I haven't tried it yet because I am assuming it doesn't.

Best,
Austin

**Comment by Jintin** [comment]
Swift 3.0 is also supportted since we don't care the real syntax, Swimat just arrange the structure.
It has pros & cons, but you don't have to worry about the swift version now.

**Comment by rajkapoordev** [comment]
Its not working for me i have download and build then its does not appear in edit menu in xcode
Its give an console logs
Message from debugger: cannot attach to process due to System Integrity Protection

**Comment by samsuk1973** [comment]
I am also facing same issue in updating xcode to 8.0 and os and its stop working

**Comment by Jintin** [comment]
I think it's not due to swift3, it the xcode extension doesn't work.
But I currently have no idea what is the right step to help you guys.
I've post a question to stackoverflow you may like help to up vote.
http://stackoverflow.com/questions/39807022/xcode8-extension

**Comment by Jintin** [comment]
@samsuk1973 @rajkapoordev can you use this link to download archive app and try again.
https://github.com/Jintin/Swimat/releases/download/v1.0/Swimat.zip

**Comment by jlaws** [comment]
Works for me on the latest version of Xcode and with Swift 3

**Comment by Jintin** [comment]
In fact Swift3 is doesn't matter but xcode8 does.
If you are using old version of Swimat from xcode7 you need to update to `extension` branch.
Easiest way is using `brew cask install swimat`.
Also make sure [System Preferences] -> [Extensions] -> [Xcode Source Editor] -> [Swimat] is checked. 
![](https://raw.githubusercontent.com/Jintin/Swimat/extension/README/setting.png)

**Comment by Jintin** [comment]
I'll close this now and please refer to https://github.com/Jintin/Swimat/issues/123
It's welcome to reopen it if any problem occurs.

**Comment by SiddharthChopra** [comment]
Hello Jintin
Its not working for me i have download and build then its does not appear in edit menu in xcode
Its give an console logs
Message from debugger: cannot attach to process due to System Integrity Protection
and also used this link by downloading archive app and try again.
https://github.com/Jintin/Swimat/releases/download/v1.0/Swimat.zip

**Comment by Jintin** [comment]
@SiddharthChopra 
The archive version is now https://github.com/Jintin/Swimat/releases/download/v1.2.1/Swimat.zip
And you can use `brew cask install swimat` instead.
Let me know if it not work.

**Comment by Jintin** [comment]
@SiddharthChopra Is it work?

**Comment by SiddharthChopra** [comment]
Hello @Jintin 
Still i am not able to see in swimat in editor menu
Have one question for you:
Does this library support from edit menu -> Swimat and when we click on save button it will format file as its working on xcode 7.3 version but now when i updated to xcode 8.2 i have followed steps given in documentation i am not able to see in swimat neither in editor menu nor in edit menu so it possible to have same what we have in xcode 7.3 version, and if yes, how it can be done?

**Comment by saagarjha** [comment]
Try running `sudo /usr/libexec/xpccachectl` and rebooting.
