### ISSUE TITLE
Incorrect indentation for guard statements and comments

### ISSUE THREAD

**Issue by saagarjha** [Jintin/Swimat#125]
Swimat seems to use incorrect indentation for guard statements that have been split into multiple lines; this:

```
guard let a = Int?.none,
    let b = Int?.none else {
        return nil
}
```

becomes this:

```
guard let a = Int?.none,
    let b = Int?.none else {
        return nil
    } // notice the extra indent here
```

I'm using the Xcode source editor extension, by the way.

**Comment by saagarjha** [comment]
Piling on, I'm seeing incorrect behavior after comments with a dot in them:

```
// A comment with a period after it.
let a = 1
```

becomes:

```
// A comment with a period after it.
    let a = 1
```

**Comment by Jintin** [comment]
Please update your extension and try again. 
Thank you for your feedback.

**Comment by saagarjha** [comment]
Unfortunately, the fix doesn't seem to really work. Thanks for the quick response though!

**Comment by Jintin** [comment]
I think its the update issue, I can't update my either.
But if you run the extension to start a black Xcode.
You should notice the update.

**Comment by saagarjha** [comment]
Yes, that's what I've been doing; unfortunately that doesn't seem to do anything.

**Comment by Jintin** [comment]
I think I found the update process.
Could you help to try these step.
- update to latest code
- run app target
- restart Xcode8

Thanks for your help.

**Comment by saagarjha** [comment]
I've added a couple of print statements, and they've been working, so I think I'm using the latest copy.

**Comment by saagarjha** [comment]
Apparently I had merge conflicts. Its works now.
