### ISSUE TITLE
Create home-brew cask for Swimat App

### ISSUE THREAD

**Issue by leolelego** [Jintin/Swimat#129]
It can be really cool to get Swimat app for Xcode 8 via homebrew cask. 

This is the documentation : https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by Jintin** [comment]
It would be great if we can support, I'll study it if I have some free time.
Thank you for your advice. ^^

**Comment by Jintin** [comment]
Sorry for the late response, you can now use `brew cask install swimat` to install Swimat.
Thank you for your info.
