### ISSUE TITLE
Switch formatting

### ISSUE THREAD

**Issue by Marsgames** [Jintin/Swimat#135]
Is there a way to format switch like this :

![image](https://cloud.githubusercontent.com/assets/9108765/21435273/354d036e-c879-11e6-8903-ff612f80dfec.png)

instead of :

![image](https://cloud.githubusercontent.com/assets/9108765/21435259/26bc4d46-c879-11e6-8e97-ef68a294e8bc.png)

I would be very gratefull if there's a way to do this.

Thank you

**Comment by Jintin** [comment]
Sure, but currently we don't have preference to modify.
Could you build on your own.
Find lines of code and change to bellow will do: 
```swift
func addIndent(addExtra: Bool = true) {
    if indent.inSwitch {
        if !isNext(words: ("case", 4), ("default:", 8)) {
            indent.extra += 1
        }
```
