### ISSUE TITLE
Format selected text only

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#137]
When using the extension, Swimat will always format the entire file, even if there is a selection.

**Comment by Jintin** [comment]
It's a good feature, but I need to figure out how to implement.
Thank you for your feedback.

**Comment by Jintin** [comment]
It fixed now. 
The logic now is if there is selection, format the start line to end line.
I think it enough for most case.
If you have other issue of it, please feel free to comment and reopen the issue.
