### ISSUE TITLE
Xcode8.2 version changes

### ISSUE THREAD

**Issue by samsuk1973** [Jintin/Swimat#138]
Hello, 
thank you for fantastic library! 
Have one question:
Does this library support from edit menu -> Swimat and when we click on save button it will format file as its working on xcode 7.3 version but now when i updated to xcode 8.2 i have followed steps given in documentation its shows me Swimat option in editor menu instead of edit menu so it possible to have same what we have in xcode 7.3 version, and if yes, how it can be done?

**Comment by Jintin** [comment]
We'll study about it, thank you for your advice.

**Comment by Jintin** [comment]
It seems editor is the place where xcode put the extension after xcode 8.X.
Does it make any different for you. You can make a hot key link to the action.

**Comment by Jintin** [comment]
And the format on save function I have no clue how to do it right now. 
Will noted in #165 and close this issue.
You can reopen or post a new one if you have further question.
