### ISSUE TITLE
Improper formatting of ternary operator

### ISSUE THREAD

**Issue by AaronBratcher** [Jintin/Swimat#14]
Love the plugin. Keep up the good work.

Problem example:

let sourceControl = (collectionView == firstStateCollectionView) ? controlsArray[indexPath.row] : source.way2DeviceControl[indexPath.row]

turns into:

let sourceControl = (collectionView == firstStateCollectionView)? controlsArray[indexPath.row]: source.way2DeviceControl[indexPath.row]

If parens are removed from the equality term, then the question mark is fine, but the colon is still mis-placed.

**Comment by Jintin** [comment]
Hi, I've test in the latest 1.4 version.

It will keep the ? and : as it original was, so if you place it in right place it will do so.
But if you place the wrong place, nothing change, either.

The complete solution might take a while, but you can skip the issue this way.
Please reinstall and reopen XCode to try again.
