### ISSUE TITLE
Crash when opening app loaded with zip file. Termination Reason: Namespace CODESIGNING, Code 0x1

### ISSUE THREAD

**Issue by ghost** [Jintin/Swimat#140]
Process:               Swimat [65041]
Path:                  /Volumes/VOLUME/*/Swimat.app/Contents/MacOS/Swimat
Identifier:            com.jintin.Swimat
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Swimat [65041]
User ID:               501

Date/Time:             2017-01-13 22:33:01.499 +0300
OS Version:            Mac OS X 10.12.2 (16C67)
Report Version:        12
Anonymous UUID:        5A643036-3C32-B308-94A2-E5ED4811CE23

Sleep/Wake UUID:       97A5CBFE-2928-42E9-A86E-2E96C9E8859B

Time Awake Since Boot: 45000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    mapped file            00000001028be000-00000001028c8000 [   40K] r-x/rwx SM=COW  

Thread 0 Crashed:
0   dyld                          	0x000000010d1ab000 _dyld_start + 0
1   ???                           	0x00000001028be000 0 + 4337688576

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5d341b68
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010d1ab000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10d1aa000 -        0x10d1e7267  dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 29288
    thread_create: 0
    thread_set_state: 8480

VM Region Summary:
ReadOnly portion of Libraries: Total=336K resident=0K(0%) swapped_out_or_unallocated=336K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                             220K        3 
__LINKEDIT                          88K        2 
__TEXT                             248K        2 
mapped file                         72K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             64.6M       12

**Comment by saagarjha** [comment]
@Jintin Confirmed the codesigning is rejected on my machine as well.
@ybabenko Would you mind checking out this version?
[Swimat.app.zip](https://github.com/Jintin/Swimat/files/706436/Swimat.app.zip)

**Comment by Jintin** [comment]
[Swimat.zip](https://github.com/Jintin/Swimat/files/706452/Swimat.zip)
@saagarjha would you like to help test if this work in your machine.
Maybe I select the wrong way to export.
Thank you.

**Comment by saagarjha** [comment]
Yes, this one seems to work fine.

**Comment by saagarjha** [comment]
@Jintin BTW, would you try #139? I've modified the codesigning mechanism, so whatever fix you used may not work with it.

**Comment by Jintin** [comment]
@saagarjha I'll look at #139 after fix all this issue, thanks for your contribute. ^^
