### ISSUE TITLE
XCode plugin fails if formatting code selected by "CMD+A"

### ISSUE THREAD

**Issue by evgzor** [Jintin/Swimat#141]
After installing swimat cli  and Xcode pluging I got error like : "Comand "Format" failed" please look attachment. In addition it crash Xcode afetre a while. Could u please assist me I did wrong?
<img width="1039" alt="screenshot 2017-01-16 14 20 44" src="https://cloud.githubusercontent.com/assets/5227456/21981203/53ddba3a-dbf7-11e6-87e1-95ae4fc6dc9a.png">

**Comment by Jintin** [comment]
Is the failed message showed in other file? 
If not, would you mind send me the file you failed private?
jintinapps@gmail.com

**Comment by evgzor** [comment]
Probably it conflicts with SwiftFormat tool. I will send the whole project (several files)

**Comment by evgzor** [comment]
The issue happened when format started after code selected by "Cmd-A".

**Comment by Jintin** [comment]
As you point out, it the range bug, if the select range contains the end line.
Thanks for reporting.

**Comment by Jintin** [comment]
As @evgzor said, issue should be closed after deployed.
And it definitely is a good suggestion so we'll keep it on before we update to `brew cask`.

**Comment by evgzor** [comment]
The issue has been fixed. It's really nice tool!
