### ISSUE TITLE
Formating compiler directives

### ISSUE THREAD

**Issue by saagarjha** [Jintin/Swimat#144]
Have you considered what to do with compiler directives? For example, how should the following code be formatted, if at all?

```swift
#if os(iOS)
	print("foo")
#endif
```

**Comment by Jintin** [comment]
Can we list all the case start with #, and we'll find a proper way to do it.
I think there is an error before about #, so I decide not to format for a while.

**Comment by Jintin** [comment]
I treat `#if` as `if` and apple indent does the same way.
Maybe we'll discuss this after we have the custom format rule.
Since I don't want to break to much from the classic way. #9
