### ISSUE TITLE
Format function call.

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#147]
Sometime we have a long function call like:

```Swift
something.callSomeFunction(arg1: anyWayToGenerateParam(), arg2: anotherParam, arg3: aVeryLongParam)
```

So, I want to break it to multiple lines:

```Swift
something.callSomeFunction(
    arg1: anyWayToGenerateParam(),
    arg2: anotherParam,
    arg3: aVeryLongParam)
```

In old swimat (with Xcode 7), it's awesome.
But in the extension branch (with Xcode 8), the args are always align with the parentheses:

```Swift
something.callSomeFunction(
                           arg1: anyWayToGenerateParam(),
                           arg2: anotherParam,
                           arg3: aVeryLongParam)
```

I suggest that if the first argument and called in the same line, then all others will align with it.
Otherwise, all args will indent 4 spaces.

Formatted example:

```Swift
something.callSomeFunction(arg1: anyWayToGenerateParam(), // in the same line
                           arg2: anotherParam, // align with first argument
                           arg3: aVeryLongParam)

// or

something.callSomeFunction(
    arg1: anyWayToGenerateParam(), // always indent 4 spaces (none of the parentheses)
    arg2: anotherParam,
    arg3: aVeryLongParam)
```

**Comment by PMExtra** [comment]
I found a very "ugly" case:

Before format:

```Swift
        let chain = UIView.animateAndChain(
            withDuration: 1.0,
            delay: 2.0,
            options: .curveEaseInOut,
            animations: {
                slideHideTitle()
                self.view.layoutIfNeeded()
            },
            completion: nil)
```

Formatted with swimat:

```Swift
        let chain = UIView.animateAndChain(
                                            withDuration: 1.0,
                                            delay: 2.0,
                                            options: .curveEaseInOut,
                                            animations: {
            slideHideTitle()
            self.view.layoutIfNeeded()
        },
                                            completion: nil)
```

I wish it will improve.

**Comment by Jintin** [comment]
Sure we will, thanks for sharing.

**Comment by Jintin** [comment]
I fix the bug, but not apply the dynamic align rule yet.
Your suggestion is very good for less config, but I'm wondering if other developers will confuse about the convention. And I'd prefer not to affect many people as possible. We have several choices now.

1. remove parameter align
2. config in somewhere like `Swimat.app`
3. if `(` come with newline than align
4. if `(` not come with newline than align 

What do you think? `2`, `3`, `4` are all good answer for me.
And is there anybody have other opinion than this four?

```swift
        let chain = UIView.animateAndChain(
                                           withDuration: 1.0,
                                           delay: 2.0,
                                           options: .curveEaseInOut,
                                           animations: {
                                               slideHideTitle()
                                               self.view.layoutIfNeeded()
                                           },
                                           completion: nil)
```

**Comment by PMExtra** [comment]
Awesome! I've tried to find a config in `Swimat.app`. It's a very humanism design.

**Comment by saagarjha** [comment]
@Jintin I prefer Option 3. I actually dislike aligning, but I'm sure there are those who use it; keeping it for those who like it is probably the best way to deal with this. I'm not sure we should add an option, at least not yet, since Swimat is rather conservative in its formatting rules: https://github.com/Jintin/Swimat/issues/9#issuecomment-193403123. (Though, if were to add options, now would probably be the time since this is probably the most controversial rule that Swimat handles.)

**Comment by Jintin** [comment]
@PMExtra I'd add config for first stage.
@saagarjha you can check if you want to update command line part. It will remain same result(parameter align) which if fine for me.

**Comment by Jintin** [comment]
Please try v1.3 again, thank you for your feedback.
