### ISSUE TITLE
Bug: distinct( ==) vs distinct(==)

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#148]
Sometimes we use the operator as a closure(or function?) in params.

For example: `array.distinct { $0 == $1 }` is equals to `array.distinct(==)`

But in this case, the swimat will insert a space before `==`.

I think if the operator is after `(`, the space should be deleted.

**Comment by Jintin** [comment]
Thank you for your feedback.

**Comment by Jintin** [comment]
[Swimat.zip](https://github.com/Jintin/Swimat/files/752331/Swimat.zip)
Would you like to try the pre-release 1.3 version.
Thank you.
您想先試試看 1.3 版本嗎?
謝謝你

**Comment by PMExtra** [comment]
原來是台灣的大神 😂😂😂
我終於不需要寫蹩腳的英語了

**Comment by Jintin** [comment]
1.3 試用有什麼問題再跟我說
謝謝你啊

Tell me if you encounter any problem with 1.3 version.
Thank you.

**Comment by Jintin** [comment]
Please try v1.3 again, thank you for your feedback.
