### ISSUE TITLE
Support CocoaPods Installization

### ISSUE THREAD

**Issue by sotozaki** [Jintin/Swimat#149]
Hello,
Thank you for your great lib :)

I have an enhancement of this lib.
Please support CocoaPods Installization

Because, I want to format with swimat in Run Script Build Phases.
Like a https://github.com/realm/SwiftLint
> This will download the SwiftLint binaries and dependencies in Pods/ during your next pod install execution and will allow you to invoke it via ${PODS_ROOT}/SwiftLint/swiftlint in your Script Build Phases.

**Comment by Jintin** [comment]
Since Swimat is a app, you can install it separate.
you can try `brew install swimat` or open Swimat.app and click the install CLI button.
Then you have the swimat command line tool.
And we also will study how to integrate with CocoaPods.
Thank you for your feedback.

**Comment by Jintin** [comment]
I've add cocoapods support, now you can try:
```
pod 'Swimat'
```

The install path is in `${PODS_ROOT}/Swimat/swimat`.
