### ISSUE TITLE
为啥用objc来做呢?

### ISSUE THREAD

**Issue by SLboat** [Jintin/Swimat#15]
用swift不更直接嘛

**Comment by Jintin** [comment]
我本來只會swift想說找個機會練習一下
可能以後就沒機會寫objc了
不過長遠來看 可能還是會找個時間轉回去swift

**Comment by SLboat** [comment]
致敬!我把它放到我网站里了
http://see.sl088.com/wiki/Xcode%E6%8F%92%E4%BB%B6_Swimat

**Comment by Jintin** [comment]
感謝你
