### ISSUE TITLE
Bug in switch ... case ...

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#152]
My code:
```Swift
switch aEnum {
case .value1,
     .value2:
    someCode()
}
```

After swimat:
```Swift
switch aEnum {
case .value1,
        .value2:
    someCode()
}
```

這裡似乎對齊`.`比較好，即使不對其也應該是縮進4個字符，而不是8個字符吧。

**Comment by PMExtra** [comment]
細想了下，因為還有其它非enum的情況（比如 case let ...）
所以我認為，規則可以是：
case 之後的代碼行都縮進5個字符，直到遇見 `:` 為止。

**Comment by Jintin** [comment]
謝謝你囉

**Comment by Jintin** [comment]
Fixed in 1.3.2, please try again.
Thank you.
