### ISSUE TITLE
New indent bug in v1.3.2 ?

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#155]
I just upgraded to v1.3.2

It is gratifying that it fixes a few bugs, but I found a new bug in this version:

```Swift
func some() -> Result {
    return f(
        arg1: value1,
        arg2: value2
    )
}
```

after Swimat:
```Swift
func some() -> Result {
    return f(
            arg1: value1,
            arg2: value2
    )
}
```

There is more of an indentation.

**Comment by Jintin** [comment]
Thank you for feedback, it should reference to https://github.com/Jintin/Swimat/commit/7ea8a58051de0052e5d38a8976523a615ae1b6d7
