### ISSUE TITLE
Grey label in editor

### ISSUE THREAD

**Issue by own2pwn** [Jintin/Swimat#156]
Hey there! I downloaded release from github, checked in pref to enable swimat, restarted my mac, but it still not enabled in xcode. I've prev. version before, but I deleted it. What can I do?

**Comment by Jintin** [comment]
Can you try delete and reinstall via `brew cask install swimat`

**Comment by saagarjha** [comment]
@own2pwn Is the issue that the "Format" menu shows up, but is grayed out?

**Comment by own2pwn** [comment]
Hey, thanks for fast reply! @Jintin 's answer did solve my problem. @saagarjha Issue was that I couldn't navigate / select swimat label which is before format
