### ISSUE TITLE
Thinking about multiline guard

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#158]
My code:
```Swift
        guard
            let fromView = transitionContext.view(forKey: .from),
            let toView = transitionContext.view(forKey: .to)
        else {
            return
        }
```

Both of Xcode indent & swimat will formatted to:

```Swift
        guard
            let fromView = transitionContext.view(forKey: .from),
            let toView = transitionContext.view(forKey: .to)
            else {
                return
        }
```

我認為前者似乎看起來更加合適？但我也懷疑我們是否應該做出一種與Xcode indent不一致的格式。

**Comment by saagarjha** [comment]
I prefer the latter, though usually my code looks more like this instead:

```swift
guard let fromView = transitionContext.view(forKey: .from),
    let toView = transitionContext.view(forKey: .to) else {
    return
}
```

There does appear to be disagreement on this; @Jintin maybe this could be added to fill up our as of now lonely preferences?

**Comment by Jintin** [comment]
I prefer the latter, also.
`guard` should be the key word, `else` is just a reminder.

我懂你想要表達的排版邏輯，
但我覺得 `guard` 應該才是整個語法的關鍵，不太需要突出 `else` 的作用。
