### ISSUE TITLE
[bug] - empty screen on load?

### ISSUE THREAD

**Issue by jonchui** [Jintin/Swimat#159]
Is it supposed to be an empty screen?

![image](https://cloud.githubusercontent.com/assets/204868/23639491/29d0c8f2-028c-11e7-926b-e22d7d9de7ff.png)

I tried installing via brew and downloading directly

**Comment by saagarjha** [comment]
Swimat may be going through some UI changes at the moment, but an empty screen is certainly *not* one of them :)
If you're on the latest version (1.3.2), would you mind downloading an older version to see if the issue persists?

**Comment by Jintin** [comment]
Can you see which version it is?
![screen shot 2017-03-07 at 10 30 30 pm](https://cloud.githubusercontent.com/assets/3413874/23660871/cda8207a-0385-11e7-8436-0f2ffb1efcd2.png)
The latest version should be like this:
![screen shot 2017-03-07 at 10 32 24 pm](https://cloud.githubusercontent.com/assets/3413874/23660921/f76bd852-0385-11e7-80f5-a26dd8b6f049.png)
You can try `brew update` and `brew cask reinstall swimat` again.
Thank you for your feedback.

**Comment by Jintin** [comment]
Do you have any update?

**Comment by Jintin** [comment]
@jonchui Or could you give me the environment you use?

**Comment by Jintin** [comment]
Sorry I have to close this issue since we can't do much with it currently.
Thank for your report and hope you doing well.
