### ISSUE TITLE
自动补空白行空格

### ISSUE THREAD

**Issue by SLboat** [Jintin/Swimat#16]
xcode自己的重新空格化总是会添加空格的
![image](https://cloud.githubusercontent.com/assets/4231376/11869533/94a462f0-a4fb-11e5-9f9c-7d8f9d44ae58.png)

所以要么再调用xcode的一次,或者就补上去呢?这样空格的好处是下一行的时候保留了tab位

**Comment by Jintin** [comment]
這是個好問題 謝謝你的建議
我原本沒有考慮太多就拿掉了

請重新安裝1.4.1版本 重開XCode
謝謝你啦

It's a good question I've never think about.
1.4.1 will indent the empty line as well.
Thank you. ^^
