### ISSUE TITLE
Discuss the indent style about chained closures.

### ISSUE THREAD

**Issue by PMExtra** [Jintin/Swimat#160]
My code:
```Swift
var someLongExpressionToGetAnArray = [1, 2, 3]

someLongExpressionToGetAnArray
    .sorted { $0 > $1 }
    .map { number in
        number * 2
    }
    .map { number in
        number + 1
    }
```

After swimat:
```Swift
var someLongExpressionToGetAnArray = [1, 2, 3]

someLongExpressionToGetAnArray
    .sorted { $0 > $1 }
    .map { number in
        number * 2
    }
    .map { number in
        number + 1
}
```

The last line `}`

**Comment by saagarjha** [comment]
Hmm, what would you expect the result to be? This looks like valid trailing closure indentation to me.

**Comment by PMExtra** [comment]
@saagarjha I have edited.

**Comment by Jintin** [comment]
It's actually what apple indent now.
But it's open to discuss, if it is more appropriate.
Maybe we can add the style option to preference in `Swimat.app` in the future version.

**Comment by saagarjha** [comment]
To be honest, I'd rewrite your example as:

```swift
var someLongExpressionToGetAnArray = [1, 2, 3]

someLongExpressionToGetAnArray.sorted(>).map { number in
	number * 2 + 1
}
```
 or, keeping your method calls:

```swift
var someLongExpressionToGetAnArray = [1, 2, 3]

someLongExpressionToGetAnArray.sorted {
	$0 > $1
}.map { number in
	number * 2
}.map { number in
	number + 1
}
```

**Comment by PMExtra** [comment]
@saagarjha Yep, I just make a simple example to illustrate the problem. Usually I use the `RxSwift` is very common to make a chained calls that had dozens of lines.
But thanks for your advice. Just I think it cannot solve this problem, when I have code like this:

```Swift
someLongExpressionToGetAnArray.map { (number) in
	sqrt(number) + 1
}.sorted(>).forEach { (answer) in
        print(answer)
}
```

This is not as intuitive as the next：

```Swift
someLongExpressionToGetAnArray
    .map { (number) in
	sqrt(number) + 1
    }
    .sorted(>)
    .forEach { (answer) in
        print(answer)
    }
```

When the call is more complex, the difference will be more obvious. How do you feel?

**Comment by saagarjha** [comment]
Well, it's a stylistic choice. @Jintin we might activate this behavior if the next method call is indented:

```swift
foo
	.bar { _ in
		print("bar")
	}
	.baz { _ in
		print("baz")
	}
```

and turn it off if it's not:

```swift
foo
.bar { _ in
	print("bar")
}
.baz { _ in
	print("baz")
}
```

**Comment by Jintin** [comment]
I think the second one is not clear enough.
```swift
foo
.bar { _ in
	print("bar")
}
.baz { _ in
	print("baz")
}
```

I think the two case to discuss is the following:
```swift
//option 1
foo
    .bar { _ in
        print("bar")
    }
    .baz { _ in
        print("baz")
}

//option 2
foo
    .bar { _ in
        print("bar")
    }
    .baz { _ in
        print("baz")
    }
```

**Comment by PMExtra** [comment]
I preferred the option 2 beacause "Where to start, where is the end.". I think the `}` will be aligned with the line contains `{`.

**Comment by Jintin** [comment]
I also like the option 2, but maybe we can discuss this after we have the custom format rule.
Since I don't want to break to much from the classic way. #9
