### ISSUE TITLE
Can't install. No swimat option in xcode

### ISSUE THREAD

**Issue by melinasparks** [Jintin/Swimat#161]
I installed swimat using "brew cask install swimat" and it all installed correctly. The problem is, in xcode 8.2 it's not showing swimat in the editor dropdown. It's also not showing up as an extension in the system preferences for OSX El Capitan.

**Comment by saagarjha** [comment]
Would you mind running `sudo /usr/libexec/xpccachectl` and rebooting? OS X El Capitan has issues loading plugins sometimes.

**Comment by afrueh** [comment]
@melinasparks Try to open Swimat once directly by going to your applications or by using spotlight. Afterwards i was able to see it in the OSX extension settings as described in the readme.

**Comment by Jintin** [comment]
Added to README. Thank you @melinasparks

**Comment by royherma** [comment]
Same issue.. installed, openned swimat.app and installed there as well, didn't appear in Extensions, then ran the command @saagarjha wrote, still no help. Using El Capitain 10.11.5

Any ideas? @Jintin

**Comment by Jintin** [comment]
Did you reboot? @royherma

**Comment by royherma** [comment]
Yes, twice!

**Comment by afrueh** [comment]
@royherma - i forgot to add that we had the same issue with El Capitan and it started working with Sierra.
