### ISSUE TITLE
Configuration to automatically remove line-end semicolons

### ISSUE THREAD

**Issue by Janglinator** [Jintin/Swimat#166]
I love Swimat, great job!

I do have a feature request:  I'm a C# dev, and line-end semicolons are in my blood.  However Swift is such a neat language, and looks even better without semicolons.  I'm trying to fight the habit, but I switch between Xamarin projects and native projects so often, it's a hard habit to kick.

Is it possible to add an option that instructs the formatter to remove line-ending semicolons?

**Comment by Jintin** [comment]
Sure we can.
Thanks for sharing it.

**Comment by Jintin** [comment]
Please update to `v1.3.5` and try again. 
Thank you fro your report.
