### ISSUE TITLE
Swimat not formatting swift code from .playground file

### ISSUE THREAD

**Issue by dingty-zz** [Jintin/Swimat#167]
Not sure if this has been resolved but Xcode 8.3.3 doesn't format swift code within playground while Swimat/Format is clicked.

**Comment by saagarjha** [comment]
Hmm…I can't reproduce this. Could you:

1. Try formatting a regular Swift file in Xcode 8.3.3?
2. Attach the playground here?
3. Restart Xcode and see if the issue persists?

**Comment by dingty-zz** [comment]
1. a regular Swift works; a playground page with Swift also
2. doesn't work for even a simple "xcplaygroundpage"
3. yes
So the problem is if the tool works with playground page as well.

**Comment by Jintin** [comment]
Hi, I'm confusing with 'xcplaygroundpage' and 'a playground page'
As I know, there is only one playground.
Do I miss anything?
Thank you for your feedback.

**Comment by saagarjha** [comment]
@dingty Thank you for the clarification, I understand the issue now.
@Jintin Playgrounds can have multiple pages, which is throwing the content UTI checker off. I'll take a look at it after I finish working on #157 and migrating to Swift 4/Xcode 9.

**Comment by Jintin** [comment]
Thank you @saagarjha the uti is `com.apple.dt.playgroundpage`
And will fix in v1.3.5

**Comment by Jintin** [comment]
Please update to `v1.3.5` and try again. 
Thank you fro your report.
