### ISSUE TITLE
Incorrect formatting: enums in switch and minuses

### ISSUE THREAD

**Issue by vysotsky** [Jintin/Swimat#17]
Hi! First of all I have to thank you for this plugin. It's awesome! I was really happy to know that there's this one. But there are two issues I have by using it:
1. When I tried to format code with enums in switch statement, the plugin deleted all tabulation;
2. If I'm using code like "let secondInt = -firstInt" plugin puts a space between "-" and the expression.
Hope this helps to make this plugin better!

If you have any questions, please let me know and I'll try to help if I can.
Thanks!

**Comment by Jintin** [comment]
Hi, are you using the latest version?
It's seems fixed in previous commits.

You can try to reinstall and reopen XCode, if there is other question please feel free to let me know.
Thank you very much.

**Comment by vysotsky** [comment]
Hi! Sorry that I wasn't responding all this time! 
Cool! You've fixed the issues above but I have another issue.
For example, if I need to format code like the following:
if -firstValue > secondValue {
} 
The code will be broken. It'll be cool if you fix it.
And thanks for your quick response and bug fixes! I think this plugin will be great! :+1:

**Comment by Jintin** [comment]
Please try 1.6.2.
Thank you for your kind.
