### ISSUE TITLE
Add a choice for 2-widths Tab?

### ISSUE THREAD

**Issue by zjzsliyang** [Jintin/Swimat#177]
Could it add a choice for 2-widths Tab just like follows:
```Swift
class ViewController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
  }
}
```
Thanks!

**Comment by saagarjha** [comment]
Swimat automatically detects indentation from context. If your code is indented with 2 spaces, that is what Swimat will use.

**Comment by zjzsliyang** [comment]
Oh, I see. Thank you.
