### ISSUE TITLE
Not support this format "if ...  else ..."

### ISSUE THREAD

**Issue by cyhhao** [Jintin/Swimat#178]
```swift
if a == 1 {
    a = 2
} 
else {
    a = 3
}
// right
```

```swift
if a == 1 {
    a = 2
}
    else {
        a = 3
}
// wrong
```

![image](https://user-images.githubusercontent.com/5381613/29701508-bccdfb90-899e-11e7-9249-3f0114821e73.png)

**Comment by Jintin** [comment]
This is not a common format for swift, I'll try to fix in next version v1.4.1.
Thanks for your report.

**Comment by cyhhao** [comment]
Thanks !

**Comment by Jintin** [comment]
please try 1.5.0. Thank you.
