### ISSUE TITLE
Xcode9 Support?

### ISSUE THREAD

**Issue by n1celee** [Jintin/Swimat#180]
Is there gonna have a update for xcode9?

**Comment by saagarjha** [comment]
Swimat supports Xcode 9. Is there something that doesn’t work?

**Comment by n1celee** [comment]
hotkey works fine, but can not find swimat under editor menu.

**Comment by saagarjha** [comment]
Hmm, interesting. Does it show up if you search for it under the "Help" menu?

**Comment by weakfl** [comment]
I have a similar problem with Xcode 9. The menu item is available, but nothing happens if I click on 'Editor -> Swimat -> Format'.
I've started the Swimat App after installation and made sure the extension is enabled. It used to work fine on Xcode 8.

**Comment by Jintin** [comment]
@weakfl what is your OS version?
And Did you see Swimat in System preference -> Extensions ?

**Comment by weakfl** [comment]
@Jintin I'm on 10.12.6 (Sierra). The extension is enabled, I even tried to disable and re-enable it.

**Comment by SeanRobinson159** [comment]
I am having the same issue. 
Not in the Editor menu OR the System Preference -> Extensions list. 

It was working perfectly on Xcode 9 and Sierra. Then I updated to High Sierra, and then it was showing in the Editor menu, but it was grayed out. So I deleted it, and reinstalled Swimat. Now it is gone from the menu and system preferences.

**Comment by Jintin** [comment]
I face the same problem when I update to High Sierra with xcode 9(9A235).

**Comment by saagarjha** [comment]
Interesting. Do other extensions work?

**Comment by Jintin** [comment]
I found a reference app
https://github.com/seanhenry/SwiftMockGeneratorForXcode
But need to wait until 10/10 since I'll get back my mac.

**Comment by weakfl** [comment]
@saagarjha Yes, other extensions are working. I'm using clang-format for objective-c code, no problems whatsoever.

**Comment by Jintin** [comment]
[Swimat.zip](https://github.com/Jintin/Swimat/files/1368823/Swimat.zip)
Can anyone confirm if the new build solved this problem.
Thanks very much.

**Comment by SeanRobinson159** [comment]
That did not work for me with Xcode Version 9.0 (9A235), macOS 10.13 (17A365)

**Comment by weakfl** [comment]
@Jintin Didn't work for me neither.

**Comment by SeanRobinson159** [comment]
After I updated to the macOS Supplemental Update (Version 10.13 (17A405)), Swimat Version 1.5.1 (15) is now working in Xcode Version 9.0 (9A235).

**Comment by Jintin** [comment]
@SeanRobinson159 @weakfl @sylee23 
I also tried on my mac, after updated to the macOS Supplemental Update the old version 1.5.0 can work properly.
So that forget about the 1.5.1
Thanks everyone.
