### ISSUE TITLE
What exactly Swimat do ?

### ISSUE THREAD

**Issue by dhlavaty** [Jintin/Swimat#181]
I have installed Swimat for the first time, and tried it. And I'm a bit surprised.

First thing I've tried to format was:

````
mutating
     func
         shuffle() {
}
````

and expected to see this of course:

````
mutating func shuffle() {
}
````

But no, the code looks like:

````
mutating
func
shuffle() {
}
````

It is a bug (seems to me) or an intention ?

I'm quite new in iOS/Swift development, I'm used to different behaviour of code formatters that I commonly use ([gofmt](https://golang.org/cmd/gofmt/) for GoLang or [Prettier](https://github.com/prettier/prettier) for javascript).

**Comment by Jintin** [comment]
Currently, Swimat didn't parse the syntax but only the structure.
So it didn't know what different between `mutating` `func` and `shuffle`.
All the rule is pre-defined, so it can only recognize some built-in key word like `if` `else` `{`... etc.
`mutating` `func` and `shuffle` is a very good example we can keep moving on.
