### ISSUE TITLE
You can’t open the application “Xcode” because it is being updated.

### ISSUE THREAD

**Issue by sadiq81** [Jintin/Swimat#186]
After installing i cant open xcode anymore.

**Comment by saagarjha** [comment]
Are you sure this is due to installing Swimat? From the error, it seems like your Xcode is being updated.

**Comment by Jintin** [comment]
The information is not enough, do you you still have this problem?

**Comment by Jintin** [comment]
I'll close it for now, you can reopen if you have any new info.
Thanks for feedback anyway.
