### ISSUE TITLE
Stopped working in macOS 10.13.3 (17D47) Xcode Version 9.2 (9C40b)

### ISSUE THREAD

**Issue by firetrap** [Jintin/Swimat#187]
Extensions doesn't show up since last macOS update.
I think it's not a issue in Swimat but at the moment i can't find any related issues anywhere

![screen shot 2018-01-30 at 12 17 58](https://user-images.githubusercontent.com/655828/35565983-a3fd23da-05b7-11e8-92db-26cf8fbec9ef.png)

**Comment by firetrap** [comment]
Reinstalled xcode and problem solved. Sorry please close the issue

**Comment by ghost** [comment]
@firetrap Reinstall is ok really ?!!?

**Comment by ssoaudaxis** [comment]
@LazyScream Rebooting worked for me.

**Comment by Jintin** [comment]
Thanks everyone.
