### ISSUE TITLE
Line end semicolon problem

### ISSUE THREAD

**Issue by larten** [Jintin/Swimat#19]
Hi,

First of all thanks for great solution for swift development!

I'm using semicolons at the end of lines, but swimat insert a space between end character and semicolon.
Can you remove this, plesase?

Edit: It insert space only, if there is ')' before ';'

**Comment by larten** [comment]
Here is the solution:

SwiftParser.m line 449:

``` swift
        if (next == '?' || next == ':') {
            return strIndex;
        } else if (next != '.' && next != '!' && next != ';') {
            [retString keepSpace];
        }
```

I've modified the else condition with semicolon.

If I will have time at night, I will make a pull request.

**Comment by Jintin** [comment]
Sure, thanks for help and review my code.
It's my pleasure.

**Comment by larten** [comment]
I will do it, just need a few more days, because I have too much work and I would like to write a few testcase.
Thanks!

**Comment by Jintin** [comment]
Sure.
Or if you can separate into several pull request.

**Comment by Jintin** [comment]
It been a while since the issue born.
Since you will fix it, I'll close it right now.
Thanks for your contribute. ^^

**Comment by larten** [comment]
Great, thanks! Sorry for delay, I have too much work :(

**Comment by Jintin** [comment]
Since there are others face the same issue, will you send the pull request recently?
You can only send the fix part, and leave the others alone when you have free time.

**Comment by Jintin** [comment]
Do you have free time recently? Or do you mind I do it for you.

**Comment by larten** [comment]
I have a deadline tomorrow for a project. If you have time, pls commit it, I can do it only after deadline.
