### ISSUE TITLE
Set indent for '[' and '(' braces

### ISSUE THREAD

**Issue by zSOLz** [Jintin/Swimat#191]
It would be perfect to have native-like Obj-C formatting for arrays, dictionaries and conditions like this:
```
    let x = ["one",
             "two",
             "three"]

    let x = ["one" : "one-v",
             "two" : "two-v",
             "three" : "three-v"]
    
    let x = (one ||
             two ||
             three)
```
instead of:
```
    let x = ["one",
        "two",
        "three"]

    let x = ["one": "one",
        "two": "one",
        "three": "one"]

    let x = (one ||
        two ||
        three)
```
Of course if you are using newline, it should format the code as it was before:
```
    let x = [
        "one",
        "two",
        "three"
    ]

    let x = [
        "one": "one-v",
        "two": "two-v",
        "three": "three-v"]

    // Here is a little formatting bug afer Swimat:
    let x = (
        one ||
            two ||
            three
    )
```
As well it could be be customizable in options. BTW I can try to implement it.

**Comment by zSOLz** [comment]
Okay, I implemented formatting I want to have but I have no access permissions to push my branch to this repo. If you want I can push the improvement to let you finish it but there is some bugs left: It's not so easy to fix them because by fixing it I'm braking something else.

**Comment by Jintin** [comment]
You can open a pr for it. we can discuss there.
Sorry about the late response.
