### ISSUE TITLE
Generics formatting issue

### ISSUE THREAD

**Issue by andrei-kuzma** [Jintin/Swimat#192]
```
public class Test: Base<Router, MediaGroupServiceProvider & NavigationServiceProvider> {

}
```
is formatted to 
```
public class Test: Base < Router, MediaGroupServiceProvider & NavigationServiceProvider > {

}
```

**Comment by Jintin** [comment]
Thanks for update, please try https://github.com/Jintin/Swimat/releases/download/v1.5.1/Swimat.zip to see if it fix your issue.

**Comment by andrei-kuzma** [comment]
Fixed. Thank you.

It would be great if 
```
public class Test: Base < Router, MediaGroupServiceProvider & NavigationServiceProvider > {

}
```
was formatted to
```
public class Test: Base<Router, MediaGroupServiceProvider & NavigationServiceProvider> {

}
```

**Comment by Jintin** [comment]
Good to know, with your contribute 1.5.1 is release to public.
You can update via your existing install method.
For the improvement request.
Currently it's difficult to format a wrong syntax, but we'll keep improve.
