### ISSUE TITLE
Enum case listing is formatted improperly

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#194]
Sorry for the ambiguous title, not exactly sure how to reference it.

In trying to auto format this:

```swift
    enum Foo {
        case
        one,
        two,
        three
    }
```

It chooses to do this:

```swift
    enum Foo {
        case
        one,
            two,
            three
    }
```

**Comment by Jintin** [comment]
Hi, according to the doc https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html
I think in this moment you can use either:
```swift
    enum Foo {
        case one,
        case two,
        case three
    }
```
or 
```swift
    enum Foo {
        case one, two, three
    }
```
And for swimat part. I don't know if this is a good format rule practice, but apple seems format this way even in switch.

```swift
    enum Foo {
        case
        one,
        two,
        three
    }

    switch foo {
    case
    .one,
    .two,
    .three:
    }
```
One reasonable way to correct it is
```swift
    enum Foo {
        case
            one,
            two,
            three
    }
```
Do you think this is better or not?

**Comment by bdrelling** [comment]
I think my expectation is that all of these work:

_Note that the first one doesn't have trailing commas because `case` is declared at the start of each line._

```
    enum Foo {
        case one
        case two
        case three
    }
```
```
    enum Foo {
        case one, two, three
    }
```
```
    enum Foo {
        case
        one,
        two,
        three
    }
```

Does this help?

**Comment by Jintin** [comment]
Thanks

**Comment by Jintin** [comment]
Build 1.5.3 will release recently, you can try here first or wait for other install method like brew cask.
https://github.com/Jintin/Swimat/releases/tag/v1.5.3
