### ISSUE TITLE
Option to indentation?

### ISSUE THREAD

**Issue by siuying** [Jintin/Swimat#2]
Currently Swimat use tab to indent, when I used on my code which is indent in space, it create a big mess that combine tab and space.

Can we choose to use tab or space to indent?

**Comment by Jintin** [comment]
Sure. Since you build it yourself, I think you can modify the code your own.
in SwiftParser.m  line: 382
`[editString appendString:@"\t"];` to `[editString appendString:@"  "];`
And for other people, maybe I'll put a switch in later version.
Thank you.

**Comment by siuying** [comment]
Thanks!!

**Comment by Jintin** [comment]
Hi, you can try the latest version 1.5.0 for indent choice.
There are three option: Tab, 2 Space, 4 Space.
If you have any further question, please feel free to let me know.
Thank you for sharing your opinion.
