### ISSUE TITLE
Add objc?

### ISSUE THREAD

**Issue by CaramelHeaven** [Jintin/Swimat#204]
What do u think about adding an objc formatter to this project?

**Comment by Jintin** [comment]
if there's any existing one we can easily integrate I think we can do it.

**Comment by bstillitano** [comment]
https://github.com/travisjeffery/ClangFormat-Xcode

**Comment by CaramelHeaven** [comment]
@bstillitano If you want use normal and fast format-plugin - just look for xcformat in app store.

**Comment by Jintin** [comment]
@CaramelHeaven thanks for your sharing, I think it's a good option to keep Swimat have less dependency on others. I'll close this for now, let me know if we have any better options.
