### ISSUE TITLE
Swift 5 #""# support

### ISSUE THREAD

**Issue by Daocheng** [Jintin/Swimat#210]
When dealing with code like
`webView.evaluateJavaScript(#"window.dispatchEvent(new CustomEvent("webview:active"));"#, completionHandler: nil)`

Swimat insert a space wrongly.
`webView.evaluateJavaScript(#"window.dispatchEvent(new CustomEvent("webview: active"));"#, completionHandler: nil)`

**Comment by Jintin** [comment]
Is `#"` a new start of String indicator?

**Comment by Daocheng** [comment]
See more details.
https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md
