### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by heart** [Jintin/Swimat#213]
I can install from the Readme instruction but I don't know how to use it

**Comment by Jintin** [comment]
The action trigger point is in Xcode menu 
<img width="740" alt="Screen Shot 2019-09-06 at 11 21 19 PM" src="https://user-images.githubusercontent.com/3413874/64439687-23f3e300-d0fd-11e9-9fde-babe598d7278.png">

**Comment by Jintin** [comment]
Please advice if the modification is much easier to understand?
https://github.com/Jintin/Swimat/pull/214/files

**Comment by heart** [comment]
> Please advice if the modification is much easier to understand?
> https://github.com/Jintin/Swimat/pull/214/files

Thank you for your hard work
