### ISSUE TITLE
Xcode 11

### ISSUE THREAD

**Issue by vityapoekhal** [Jintin/Swimat#215]
Hi!

I appreciate using Swimat, but since Xcode update, it's grayed out in menu. Any ideas?
<img width="265" alt="Screenshot 2019-10-04 at 09 12 13" src="https://user-images.githubusercontent.com/3634154/66185232-6f12fe80-e687-11e9-9c5b-61efcae3e90e.png">

Thanks!

**Comment by akuzminskyi** [comment]
@victorhydecode Hi, for me it works well. Verify that you have selected "Swimat" in macOS Preferences. https://github.com/Jintin/Swimat#troubleshooting

**Comment by vityapoekhal** [comment]
@akuzminskyi Hi! Thanks. Yes, I checked it first thing. Even tried to disable -> restart Xcode -> enable -> restart Xcode. Still grayed out.
![Screenshot 2019-10-04 at 09 23 22](https://user-images.githubusercontent.com/3634154/66185766-18a6bf80-e689-11e9-900b-7688b72de3fa.png)

**Comment by vityapoekhal** [comment]
Update: removed Swimat with [AppCleaner](https://freemacsoft.net/appcleaner/) to reinstall it. After installation (tried both via archive from GitHub and via brew cask) doesn't appear in Extension Preferences. What a day (

**Comment by vityapoekhal** [comment]
After Xcode updated to 11.1 the problem disappeared.
