### ISSUE TITLE
Removing semicolons does not work

### ISSUE THREAD

**Issue by apacha** [Jintin/Swimat#219]
When opening the app and selecting "Remove semicolons" in the options, the program forgets this selection immediately and semicolons are not removed when auto-formatting in XCode.

I'm using Version 1.15.1 (15) that I downloaded from Github.

**Comment by Jintin** [comment]
It's quite old build, would you like to try latest build?
And do you mean auto-formatting is the IDE formatting or Swimat does?

**Comment by apacha** [comment]
It works with the newest version. I actually downloaded the old version, because it was linked from the README. It would be great if you could update that to reference to the latest version.
