### ISSUE TITLE
Xcode 12 support on macOS 11

### ISSUE THREAD

**Issue by hyperphonic0** [Jintin/Swimat#224]
**What is the issue**
Extension does not work with Xcode 12, the Editor > Swimat menu item is not present.

**Expected behaviour**
The Editor > Swimat entry does not appear

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Xcode 12
 - App Version [e.g. 1.6.2]

**Additional context**
XcodeKit.framework needs to be added to the extension target (Embed without signing), then the extension will function again in Xcode 12.

**Comment by sourcelocation** [comment]
Hi. Is there any workaround?

**Comment by hyperphonic0** [comment]
Yes, it's merged already.

(So I guess this should be closed!)

**Comment by hyperphonic0** [comment]
Resolved by #225 .

**Comment by hyperphonic0** [comment]
Revised issue title... new macOS security features were preventing the extension from running.

From the Xcode 12 Beta 2 Release Notes:

> ### Source Editor
>**Known Issues**
>A new Xcode Source Editor Extension target does not automatically set up embedding XcodeKit.framework in the extension. (59274389)
>_Workaround: Embed XcodeKit.framework in the extension manually._
>
>An Xcode extension may cause Xcode to hang on launch, or upon enabling the extension. (61952790)
>_Workaround: Disable the Xcode extension in the Extensions pane in System Preferences._
>
>**Deprecations**
>For compatibility with new security features in macOS 11, Xcode extensions must be built using Xcode 12 and must embed XcodeKit.framework. An Xcode extension rebuilt with these tools remains compatible with older versions of Xcode and macOS. (51822755)

**Comment by St1ggy** [comment]
I have not Swimat in Editor in Xcode 12 :(
<details>
<summary>Xcode 11</summary>
<img width="281" alt="Screenshot 2020-08-27 at 21 51 12" src="https://user-images.githubusercontent.com/13361661/91458327-94b48200-e8af-11ea-8afa-9048bfd91378.png">
</details>

<details>
<summary>Xcode 12</summary>
<img width="287" alt="Screenshot 2020-08-27 at 21 51 23" src="https://user-images.githubusercontent.com/13361661/91458343-9d0cbd00-e8af-11ea-825c-82bc93a562a2.png">
</details>

**Comment by hyperphonic0** [comment]
Did you build Swimat from source?

If you didn't then do that (I don't think the fix is in a built release yet).

**Another possibility**
There are sometimes problems (with all extensions, not just swimat) if you have two installations of Xcode on your machine at once.

check the output of:

`xcode-select -p`

(will be something like: `/Applications/Xcode.app/Contents/Developer`)

Make sure this matches the Xcode 12 path.

Change if necessary with:

`sudo xcode-select -s <NEW DEVELOPER FOLDER PATH>`

For example:

`sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`

Then check all the usual things for extensions (e.g. that they are enabled, security, ...).

**Comment by St1ggy** [comment]
> Did you build Swimat from source?
> 
> 
> 
> If you didn't then do that (I don't think the fix is in a built release yet).
> 
> 
> 
> **Another possibility**
> 
> There are sometimes problems (with all extensions, not just swimat) if you have two installations of Xcode on your machine at once.
> 
> 
> 
> check the output of:
> 
> 
> 
> `xcode-select -p`
> 
> 
> 
> (will be something like: `/Applications/Xcode.app/Contents/Developer`)
> 
> 
> 
> Make sure this matches the Xcode 12 path.
> 
> 
> 
> Change if necessary with:
> 
> 
> 
> `sudo xcode-select -s <NEW DEVELOPER FOLDER PATH>`
> 
> 
> 
> For example:
> 
> 
> 
> `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`
> 
> 
> 
> Then check all the usual things for extensions (e.g. that they are enabled, security, ...).
> 
> 

Yeah, thank you! I've just built it with Xcode 12 and XcodeKit.framework and it works now!
