### ISSUE TITLE
cant open swimat

### ISSUE THREAD

**Issue by NikhilGangurde** [Jintin/Swimat#232]
**What is the issue**
“Swimat.app” can’t be opened because Apple cannot check it for malicious software.

**Desktop:**
 - OS: 11.0.1
 - App Version: Latest
 - Xcode: 12.0.1

**Additional context**
Unable to open the app and also swimat was disabled in the code editor menu.
Installed via "brew install --cask swimat".
<img width="372" alt="Screenshot 2020-12-25 at 12 24 50 PM" src="https://user-images.githubusercontent.com/46920378/103124010-3ad09700-46ac-11eb-842e-5fcd092821c8.png">

**Comment by Jintin** [comment]
So how do you fix this?

**Comment by kkankala** [comment]
Follow these steps:

1. Click on show in finder
2. right click on swimat.app and click open
3. click install swimat to '/usr...' 

Good luck!
