### ISSUE TITLE
No Swimat in Editor menu

### ISSUE THREAD

**Issue by stantestov** [Jintin/Swimat#233]
No Swimat in Editor menu.
I'm enabled extension in System preference and do all instructions

**Expected behavior**
Maybe it's a M1 chip problem

**Desktop (please complete the following information):**
 - OS: Big Sur 11.2.3, 20D91
 - App Version  1.6.2

Xcode Version 12.4 (12D4e)

**Comment by saagarjha** [comment]
What happens if you restart Xcode?

**Comment by stantestov** [comment]
Nothing. I was restarting my Mac too. Can send you a video 

Testov Stanislav

**Comment by saagarjha** [comment]
I noticed you're not on the latest version of the app. Can you try updating?

**Comment by stantestov** [comment]
I reinstall it by homebrew and it works! Thank you!
