### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by CodeEagle** [Jintin/Swimat#24]
auto format will turn 
`#if (arch(i386) || arch(x86_64)) && os(iOS)`
to 
`#if(arch(i386) || arch(x86_64)) && os(iOS)`
error when build

**Comment by CodeEagle** [comment]
error  gloss
`"post_id" <~~ json`
to
`"post_id" < ~~ json`

**Comment by Jintin** [comment]
is `<~~` an operation?
And why your code has `#` start?

**Comment by CodeEagle** [comment]
from [Gloss](https://github.com/hkellaway/Gloss)
`~~>`
`<~~`
both

**Comment by Jintin** [comment]
OK I got it,
but why your code has # start?

**Comment by CodeEagle** [comment]
not swift code `#if`, is a macro
look [here](http://stackoverflow.com/questions/24003291/ifdef-replacement-in-swift-language)

**Comment by Jintin** [comment]
Thank for your explain.
Please reinstall and try again.
Let me know if it fix in 1.7.1.

**Comment by CodeEagle** [comment]
good job

**Comment by CodeEagle** [comment]
hey look at this
inline `{get}` should be `{ get }`
inline `{return}` should be `{ return }`
inline `{get set}` should be `{ get set }`

**Comment by Jintin** [comment]
Thanks again.
You can check the 1.7.3.
Also tell me if it works.

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/12372843/c287ce30-bc9f-11e5-85bc-bb59ae346198.png)
still need improve

**Comment by Jintin** [comment]
My fault, please try again.
^^

**Comment by CodeEagle** [comment]
`>  - 1` should be `> -1`
and for`<` `!=` `==` and so on
and sth like`let x = -width/2` is wrong display `let x = - width / 2`

**Comment by Jintin** [comment]
Please try 1.7.10.
Thank you for your feedback.

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/13028183/44c0b138-d2a2-11e5-8372-7886af523b76.png)
here comes new one
should be  `province["s"].arrayValue[row]["n"].stringValue`
no space between `[][]`

**Comment by Jintin** [comment]
Thank you.
Please try 1.8.1.

**Comment by CodeEagle** [comment]
`if let pool = NSKeyedUnarchiver.unarchiveObjectWithFile(SongCacheManager.configSourcePoolPath()) as ? [String : AnyObject]`

should be `as?` not `as ?`

**Comment by Jintin** [comment]
It fix in previous commit, please reinstall and try again.

**Comment by CodeEagle** [comment]
`reloadDataWithCompletion({ done?()})` -> `reloadDataWithCompletion({ done?() })`

`flatMap({ $0}))` -> `flatMap({ $0 }))`

**Comment by Jintin** [comment]
Please try 1.8.6. ^^

**Comment by CodeEagle** [comment]
`[String : AnyObject]` not `[String: AnyObject]`

**Comment by Jintin** [comment]
If you're talking about dictionary, it recommend to format this way.

``` swift
var namesOfIntegers = [Int: String]()
// namesOfIntegers is an empty [Int: String] dictionary
```

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html

**Comment by CodeEagle** [comment]
https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSAttributedString.swift 
Line 41 and more

**Comment by Jintin** [comment]
Yes, so there isn't a standard.
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html
If you looking all this document, it all this format:

``` swift
var airports: [String: String] = ["YYZ": "Toronto Pearson", "DUB": "Dublin"]
```

I tend to be use the document style.
And I think this is better to format and read.
Or if you have any opinion on this case?

**Comment by Jintin** [comment]
In your site, it also have:

``` swift
public class NSAttributedString : NSObject, NSCopying, NSMutableCopying, NSSecureCoding {
```

I think this man don't care about format at all.

**Comment by CodeEagle** [comment]
ok
