### ISSUE TITLE
Swimat indents empty lines

### ISSUE THREAD

**Issue by illaz** [Jintin/Swimat#25]
Hi,

first of all I'd like to thank you for your great work!

Unfortunately Swimat seems to indent empty lines if the line after is indented.
![Swimat indents empty lines](https://picload.org/image/wdcogoa/bildschirmfoto2016-01-20um09.4.png)

It would be great if Swimat could remove any unnecessary whitespace in empty lines. This would increase the code quality.

Best regards

**Comment by Jintin** [comment]
Actually, I add this function due to someone's suggestion. XD
So I think there's no correct answer about this question.
And I add a preference to it.
Please reinstall and try if it work.
Thank you.

**Comment by afrueh** [comment]
Thanks a lot! :+1:

**Comment by illaz** [comment]
Thanks!

**Comment by Jintin** [comment]
You're welcome.
