### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by gssdromen** [Jintin/Swimat#3]
![screen shot 2015-11-25 at 3 18 00 pm](https://cloud.githubusercontent.com/assets/2989634/11390729/c9d6d316-9387-11e5-830e-e21d7c04c63d.png)

any ideas? thanks

**Comment by lexrus** [comment]
+1. Same issue.

**Comment by CocoaBob** [comment]
Remove all Schemes, and only add `Swimat` back to the list. Then delete the missing `Swimat.xcscheme` file in the files list. Now we can build the project without any issue.

**Comment by Jintin** [comment]
Thank @CocoaBob, and I change the workspace to a single project.
It might easy to build right now.
