### ISSUE TITLE
Protocol declaration 

### ISSUE THREAD

**Issue by jsaguiar** [Jintin/Swimat#30]
In swift is up to you to use ";" or not (despite I think is better to not use it)

If you do this

``` swift
protocol protocolName {   
   func functionName();
}
```

it will format to;

``` swift
protocol protocolName {   
   func functionName() ;
}
```

(see the space between function name and ";") 

It was perfect if you can give the option to auto-delete ";" (for everything).

**Comment by Jintin** [comment]
Is there any description about it?

**Comment by jsaguiar** [comment]
Sorry, I just update it.

**Comment by Jintin** [comment]
Sure we can do.
There is one volunteer will do this. 
#19 @larten

**Comment by Jintin** [comment]
Please try 1.7.10.
Thank you for your feedback.

**Comment by jsaguiar** [comment]
It's working. Thank you
