### ISSUE TITLE
..< and ... operators.

### ISSUE THREAD

**Issue by charlieMonroe** [Jintin/Swimat#31]
It seems that preferred Apple way currently is that there is a space both before and after the operator:

Correct:

```
1 ..< 2
1 ... 2
```

Incorrect:

```
1..<2
1 ..<2
1...2
1 ...2
```

I'm basing this on how the autofixer in Xcode 7.3b2 behaves - the `for var i = 0; i < 3; ++i` for loop style is deprecated as of Swift 2.2 and Xcode offers automatically to replace the loop with the following: `for i in 0 ..< 3` - including the spaces.

**Comment by Jintin** [comment]
It's fix in previous commit.
Please reinstall and try again. ^^
#28

**Comment by charlieMonroe** [comment]
Thanks!
