### ISSUE TITLE
Wrong indentation 

### ISSUE THREAD

**Issue by jsaguiar** [Jintin/Swimat#32]
When you put something like 
UIView.animateWithDuration(time,
            delay: 0,
            usingSpringWithDamping: 0.8,
            initialSpringVelocity: 0,
            options: [
                UIViewAnimationOptions.AllowUserInteraction,
                UIViewAnimationOptions.CurveEaseOut],
            animations: { () -> Void in
            },
            completion: { (animated) -> Void in
            })

it indents to (removing the spaces of options array):
UIView.animateWithDuration(time,
            delay: 0,
            usingSpringWithDamping: 0.8,
            initialSpringVelocity: 0,
            options: [
            UIViewAnimationOptions.AllowUserInteraction,
            UIViewAnimationOptions.CurveEaseOut],
            animations: { () -> Void in
            },
            completion: { (animated) -> Void in
            })

**Comment by Jintin** [comment]
Please try 1.7.11.
Thank you for your feedback.

**Comment by jsaguiar** [comment]
:+1:  TY
