### ISSUE TITLE
in-line if

### ISSUE THREAD

**Issue by jsaguiar** [Jintin/Swimat#33]
let boolValue = isBool ? true: false
should indent to
let boolValue = isBool ? true : false

**Comment by jsaguiar** [comment]
i found other bug related to this...
if we need to divide this condition in multiple lines we should so something like
let value = variable != nil 
    ? true
    :  false

but it does:
let value = variable != nil 
? true
    :  false

**Comment by Jintin** [comment]
Please try 1.7.12.
Thank you. ^^

**Comment by jsaguiar** [comment]
nice :D TY
