### ISSUE TITLE
Ternary Operator Issue

### ISSUE THREAD

**Issue by jlaws** [Jintin/Swimat#35]
`self.bottomBorderLayer.backgroundColor = self.detailLabelHidden ? self.bottomBorderColor?.CGColor : self.detailLabelActiveColor?.CGColor`

gets turned into

`self.bottomBorderLayer.backgroundColor = self.detailLabelHidden ? self.bottomBorderColor ? .CGColor : self.detailLabelActiveColor?.CGColor`

which doesnt compile

**Comment by jlaws** [comment]
also this 

`self.exercisesDelegate?.updatedExercises(exerciseVC: self, exercises: self.exercises)`

turns into

`self.exercisesDelegate ? .updatedExercises(exerciseVC : self, exercises: self.exercises)`

**Comment by Jintin** [comment]
Please reinstall and try again.
But you have to revert to the correct version.
Thank you for your feedback. It really help.
