### ISSUE TITLE
if let as? issue

### ISSUE THREAD

**Issue by jlaws** [Jintin/Swimat#36]
`for set in sets {
      if let setDict = set as? [String: AnyObject],
         let workoutSet = MutableWorkoutSet.fromDictionary(setDict) {`

becomes

`for set in sets {
            if let setDict = set as ? [String : AnyObject],
                let workoutSet = MutableWorkoutSet.fromDictionary(setDict) {`

**Comment by Jintin** [comment]
Please reinstall and try again.
And you have to revert to the correct version.
Thank you for your feedback. It really help.
