### ISSUE TITLE
Nil coalescing operator issue

### ISSUE THREAD

**Issue by gowsiany** [Jintin/Swimat#37]
Hi, last version of this great plugin has following issue:

`var name: String?`
`let result = name ?? "empty"`

is reformatted to

`var name: String?`
`let result = name ? ? : "empty"`

Result: compile error.

**Comment by Jintin** [comment]
Really sorry about that.
Please try 1.7.14 and try again.
Thank you for your feedback.

**Comment by gowsiany** [comment]
It's working now!  :+1:
