### ISSUE TITLE
Preprocessor macros in Swift code

### ISSUE THREAD

**Issue by acadet** [Jintin/Swimat#39]
Hi there,

First, thank you so much for your hard work on this plugin! It's really awesome :)

Here is a bug I found: when using preprocessor macros in a Swift file (such as `#if` or `#else`), the codebase is not indented correctly. 

I have this:

``` swift
#if DEBUG
print("foo")
#else
print("bar")
#endif
```

Instead of that:

``` swift
#if DEBUG
    print("foo")
#else
    print("bar")
#endif
```

**Comment by Jintin** [comment]
Please reinstall and try v1.7.15.
Thank you for your feedback.

**Comment by acadet** [comment]
It works great! Thanks!

**Comment by Jintin** [comment]
^^
