### ISSUE TITLE
calling optional closure

### ISSUE THREAD

**Issue by jsaguiar** [Jintin/Swimat#41]
if you try to call a optional closure like: 

``` swift
closure?(String(format : "asdas"))
```

It will format to: 

``` swift
closure ? (String(format : "asdas"))
```

Causing an error on xcode.

**Comment by Jintin** [comment]
Please reinstall and try again, v1.7.17.
Inline if check is more difficult than I thought. XD

**Comment by jsaguiar** [comment]
It's working :)
TY man. Maybe this weekend I will take a look into the code, and try to help you.

**Comment by Jintin** [comment]
Sure. It would be great if you can help. ^^
