### ISSUE TITLE
Breaks when using certain custom operators

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#44]
Take a look at the popular library Eureka:

https://github.com/xmartlabs/Eureka

When trying to do +++ or >>>, it puts ++ + and >> > instead, breaking the code.

Unfortunately have to disable Swimat for now.

**Comment by Jintin** [comment]
Thank you for your feedback.
Please try 1.8.2.

**Comment by bdrelling** [comment]
This no longer breaks the code, thanks for the quick update! What a lifesaver.

Is there any way for us to customize the format on our end for these operators? Specifically, to make it look like their form:

https://github.com/xmartlabs/Eureka#how-to-create-a-form

While the formatting with Swimat doesn't break the code anymore, it does put the <<< directly indented at the same point as +++. I'm not sure what the proper way would be to handle this, and I don't really mind how it is (definitely not urgent), but is there anything to be done from our end to make it look more like the Eureka docs?

On another note, does Alcatraz update directly on launch or do I have to uninstall and reinstall the plugin? (I did the latter, but wondering if I even had to.)

Thanks again!

**Comment by Jintin** [comment]
Custom operators is a good idea.
The current logic can be optimised as well.
It might take some times, but I'll keep in mind.

The update process is also not friendly.
I reinstall all the time. (Open Alcatraz -> Remove -> Install)
