### ISSUE TITLE
Swimat formatter with command + s

### ISSUE THREAD

**Issue by lfarah** [Jintin/Swimat#51]
There are libraries [like this one](https://github.com/ThilinaHewagama/AutoIndentWithSave) where you automatically format the code when you save the project (Command + S). We could do the same, but formatting with Swimat

**Comment by Jintin** [comment]
We did provide (Command + S), you can turn on in menu [Edit] -> [Swimat] -> [Format when Save].

**Comment by violabg** [comment]
is this available on the latest version?
I can find it anymore

**Comment by Jintin** [comment]
The `extension` version is not support yet.
Sorry.
