### ISSUE TITLE
one issue

### ISSUE THREAD

**Issue by moshiwu** [Jintin/Swimat#56]
code before:
var titles:Array < Array < (icon: String, name: String, menuType: MenuList)>>?

after format:
var titles: Array < Array < (icon: String, name: String, menuType: MenuList) >> ?

then Xcode will report errors
correct code is:
var titles: Array < Array < (icon: String, name: String, menuType: MenuList) > >?

Would you please fix it?
Your plug-in is great help for me. Thank you for your working！

**Comment by Jintin** [comment]
Sure, thank you for your feedback, the generic block check logic need to be update to fit more general case.
It'll take sometime, but we indeed will fix it.
You can use typealias first, and it'll be more readable.

``` swift
typealias SomeType = (icon: String, name: String, menuType: MenuList)
typealias SomeArray = Array<SomeType>
var titles: Array<SomeArray>?
```

or

``` swift
typealias SomeType = (icon: String, name: String, menuType: MenuList)
var titles: Array<Array<SomeType>>?
```

**Comment by Jintin** [comment]
Please reinstall and try again.
Thank you for your feedback.
Tell me if there others issue.

**Comment by moshiwu** [comment]
Thank you！
