### ISSUE TITLE
Space before ending curly brace for closures within parenthesis is getting removed

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#57]
Very minor bug:

`transactions.filter({ $0.shouldCache })`

on save becomes:

`transactions.filter({ $0.shouldCache})`

**Comment by Jintin** [comment]
Please use the latest version.
I think it should fix in previous commit.
Let me know if it doesn't work.

**Comment by bdrelling** [comment]
Thanks a lot!
