### ISSUE TITLE
Swimart work incorrect

### ISSUE THREAD

**Issue by mdtuyen** [Jintin/Swimat#58]
Usually I must restart Xcode to swimart work correct.

**Comment by Jintin** [comment]
If you install or update, it is needed to restart.
If not this case, please tell me what happened.
The format not working? format in wrong way? or others.

**Comment by mdtuyen** [comment]
yes, It work fine when I start Xcode, but some minute after that I cannot make it autoformat by shift+option+command + L or from Edit > Swimat > Format
Format is wrong

**Comment by Jintin** [comment]
Format is wrong or it not working.
It's wired case that I never face.
What is your Xcode version, and if you install any other plugin?

**Comment by mdtuyen** [comment]
Yes, I use Xcode 7.2.1 beside Swimat I only use FuzzyAutocomplete plugin.

**Comment by Jintin** [comment]
Would you mind temporary uninstall FuzzyAutocomplete couple days to try if they are conflict?

**Comment by Jintin** [comment]
Do you have any update?

**Comment by Jintin** [comment]
This question is out of date, please try `extension` branch in Xcode8.
