### ISSUE TITLE
Comments within closures causing odd behavior on parenthesis

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#60]
Got latest version before checking this one:

```
for view in views! {
    // Hide either the wrapper view or the label (if view is nil)
        (view ?? self).hidden = text?.isNilOrWhitespace !== false
}
```

That is how the code formats on save, with the `(view ?? self)` being indented another step.

I've moved the comment above the for loop, but figured I'd report the stuff I found since you've been so great at maintaining this and very responsive.

Keep up the hard work!

**Comment by Jintin** [comment]
Please update and try again 1.8.8. Thank you.
