### ISSUE TITLE
Swimat is incorrectly formatting "where" within generic statement

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#62]
`class ListTransform<T: RealmSwift.Object where T: Mappable> : TransformType {`

is being formatted to

`class ArrayTransform<T: RealmSwift.ObjectwhereT: Mappable> : TransformType {`

**Comment by Jintin** [comment]
I think it same as #59 , please reinstall and try again.
Tell me if it not working.
Thank you. ^^
