### ISSUE TITLE
Mxing up the ?? operator with double optional unwrapping

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#64]
Hi!
Sometimes it's needed to do double optional unwrapping, e.g.

``` swift
let c = UIApplication.sharedApplication().delegate!.window??.rootViewController
```

(where the delegate may optionally implement a `window?` property)

Swimat currently inserts spaces around the ??, which leads to a syntax error.

**Comment by Jintin** [comment]
Thank you for your feedback.
You can try 1.8.9 now.

**Comment by entonio** [comment]
Works great, thank you!
