### ISSUE TITLE
Allow 'format selected lines'

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#65]
In teams which haven't agreed to use Swimat for everyone, it's not possible to use 'format whole file' without 'breaking' the parts written by other users. As such, it would be great if there were an option to format only the selected lines.

**Comment by Jintin** [comment]
Yes we did that function.
Please give it a try.
Thank you.

**Comment by entonio** [comment]
I see, you format the selection if there is a selection. Thanks!
