### ISSUE TITLE
Problem formatting certain strings

### ISSUE THREAD

**Issue by GabrielCartier** [Jintin/Swimat#66]
Try running Swimat on a something like this:
`let price : String = ("$\(NSString.localizedStringWithFormat("%.2f",deal.discountPrice))")`

The result is this:
`let price: String = ("$\(NSString.localizedStringWithFormat(" % .2f",deal.discountPrice))")`

Not only does it add extra spaces, but it actually break the format string.

**Comment by Jintin** [comment]
Thanks a lot. Please update to 1.8.10 and try again.

For this version, it will show:
`let price :String = ("$\(NSString.localizedStringWithFormat("%.2f",deal.discountPrice))")`

Next version(1.8.11 in two days), it will become:
`let price :String = ("$\(NSString.localizedStringWithFormat("%.2f", deal.discountPrice))")`

**Comment by Jintin** [comment]
It fix now, but still can improve.
You can reinstall and tray again.
Thank you for your feedback.
