### ISSUE TITLE
Do not indent on #if directives?

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#69]
I'm not sure of this is consensual, but from my point of view, code like

```
#if FLAG
code
#endif
```

shouldn't be indented. I'm not worried abut the #if/#endif themselves, only about the inside part.
That's because it is logically at the same level of what's outside of it, so in my opinion it huld have the same elevel of indentation it would have it here were no #if/#endif there.

**Comment by Jintin** [comment]
I treat #if as if, and so does Apple do.
You can try [cmd + A] + [control + i]
But it's open to discuss. 
Thank you for so much enthusiastic.

**Comment by Jintin** [comment]
Do anyone watch this project has any other opinion?

**Comment by entonio** [comment]
Only as in illustration, I don't worry much about the inside of methods, but to me it looks weird outside:

```
extension SomeType
{
}
```

becomes

```
#if DEBUG
    extension SomeType
    {
    }
#endif
```

**Comment by Jintin** [comment]
Yes, if you use it as outside block, it will be a little bit wired.
But the indent is one metaphor  to tell you the code is in some block ( `if debug` block).
I don't know if there have other ways to do so, but maybe the `if debug` block is not very suitable for large code block.
And if you use the Apple style indent, it will do the same thing. So I would prefer leave this indent it was.
Thank you for your opinion, wish you find a better way to do so.
^^
