### ISSUE TITLE
inconsistency formatting

### ISSUE THREAD

**Issue by Fred-J** [Jintin/Swimat#7]
swipGestureRight = UISwipeGestureRecognizer (target: self , action: Selector("swipViewRight:") )
swipGestureRight = UISwipeGestureRecognizer(target: self, action: Selector("swipViewRight:"))

the above 2 lines have passed by the formate as valid, it would be a lot better if for the sack of readability the following is adopted.
swipGestureRight = UISwipeGestureRecognizer (target: self, action: Selector("swipViewRight:"))

**Comment by Jintin** [comment]
Thank you for your report.
It's very useful suggestion for me.
I've made some change to fit this qualify.

Please reinstall and restart XCode and try in version 1.2.4.

**Comment by Fred-J** [comment]
Please submit to Alcatraz as this is how I can install it.

Another issue, notice the 2 lines below, the first is before swim at, the second after swimat has run. It actually broke the code and it will not compile.
notice the space which was removed after the operator -=

UIView.animateWithDuration(0.3, animations: {self.myLabel.center.x -= (self.myLabel.bounds.width)}, completion: nil)
UIView.animateWithDuration(0.3, animations: {self.myLabel.center.x -=(self.myLabel.bounds.width)}, completion: nil)

**Comment by Jintin** [comment]
I submit it, 

You can check the version in `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Swimat.xcplugin/Contents/Info.plist` CFBundleShortVersionString tag, it should be 1.2.5 now

Thank you for report :)

**Comment by Fred-J** [comment]
swipGestureRight = UISwipeGestureRecognizer (target: self , action: Selector("swipViewRight:") )
swipGestureRight = UISwipeGestureRecognizer(target: self, action: Selector("swipViewRight:"))

both lines above are ignored by your formatter. It would be better for readability to adopt the second line. notice there is no space between self and "," and no space between the last closing ))

**Comment by Fred-J** [comment]
BTW the latest version I just got from Alcatraz is 1.2.6 in the file you indicated and not 1.2.5 as you stated.

**Comment by Fred-J** [comment]
Another issue:
Notice that your code leaves unnecessary empty lines between 2 consecutive closing curly brackets as in the code below.
It would be a lot better if such lines are deleted.
class Icon {

```
var title: String
var subtitle: String
var image: UIImage?
var rating = RatingType.Unrated

init(withTitle title: String, subtitle: String, imageName: String?) {
    self.title = title
    self.subtitle = subtitle
    if let imageName = imageName {
        if let iconImage = UIImage(named: imageName) {
            image = iconImage
        }
    }


}
```

}

**Comment by Jintin** [comment]
The space around '(', ')' and ',' are handle in 1.3.0 version.

The newline is not handled by current design, I think in some case you need more newline to indicate something. In some IDE, it can only allow one empty line, but there are some others can two.
It may different from people to people, but I rather to leave the decision to the developer.

Thanks for sharing this idea to me, help a lot. :)

**Comment by Jintin** [comment]
Or maybe we can add preference setting to let developer setup like witch indent do you want(tab,space).

But it'll in later version.

**Comment by Fred-J** [comment]
Have you considered this formatting:

```
if _ whatever_ 
```

to

```
if _ whatever_ {
    | cursor is here ready to type
}
```

When the use hits ctrl shift enter
?

**Comment by Fred-J** [comment]
notice how your code formatted this:
    if NSFileManager.defaultManager().fileExistsAtPath(path, isDirectory: &isDirectory) {
        return true
    }else {
        return false
    }

it would be better if  there is a space between the } and "else" so that it gives:
    if NSFileManager.defaultManager().fileExistsAtPath(path, isDirectory: &isDirectory) {
        return true
    } else {
        return false
    }

**Comment by Jintin** [comment]
You can check the latest version 1.3.1.

Thanks for sharing some many idea and bug. XD

**Comment by Fred-J** [comment]
Please upload to Alcatraz

**Comment by Jintin** [comment]
push fail last time, please try again.

**Comment by Fred-J** [comment]
Are you coding any life "current line" formatting at the press of the Enter key or only on Shift + Option + Command + L ?

**Comment by Fred-J** [comment]
please note the bug below where }} is not formatted to each curly bracket on it own line property indented.

```
if somevar {
    if another {
        if yetanother {

        }}
}
```

expected:

```
if somevar {
    if another {
        if yetanother {

        }
    }
}
```

**Comment by Jintin** [comment]
In current design, we'll leave the add/remove newline to user.
For some short code case, you may want to leave them all in one line.
So we don't force decide what is correct and what isn't.

Bellow format is all valid for our parser.

```
if somevar {
    if another {
        a = b
    }
}

if somevar {
    if another {a = b}
}

if somevar 
{
    if another {a = b}
}


if somevar {
    if another {
        if yetanother {

        }} // same position as previous if
}
```

**Comment by Jintin** [comment]
Or do you think this is more better?

```
if somevar {
    if another {
        if yetanother {

    }} // same position as last bracket
}
```

**Comment by Jintin** [comment]
And for the auto gen-code part question.
I won't reject any good idea like your proposal.
But currently, I'll take more focus in the format field.

The advance operation will in next stage. Thank you.

**Comment by Fred-J** [comment]
when commenting some lines of code, swimat removes its original formatting which is not what is expected:
code:

```
if condition {
    do {
        var a = 2
    }
} 
```

after commenting:

```
//if condition {
//    do {
//        var a = 2
//    }
//}
```

swimat run:

```
// if condition {
// do {
// var a = 2
// }
// }
```

which is hard to read specially with large block of conditional code. it is better if swimat leaves it as commented

**Comment by Jintin** [comment]
Sure, please try v1.3.3 ^^

**Comment by Fred-J** [comment]
In regards to your question 2 days ago about:

```
if somevar {
    if another {
        if yetanother {

    }} // same position as last bracket
}
```

It is important to leave each curly bracket on it's new line like so:

```
if somevar {
    if another {
        if yetanother {

        }
    }
}

```

Because it will allow for the feature of a vertical line giving a hint of this particular block of code as a collection as used in many code editors and maybe in xCode later either by Apple or another plugin

**Comment by Fred-J** [comment]
When you are ready for the auto gen code Parts please let me know and I will give a lot of suggestions

**Comment by Fred-J** [comment]
I found another issue with switch case conditional statements:
here is how swimat does it:

```
        switch (indexPath.row) {
            case 0:
            print(0)
            default:
            break
        }
```

Please consider doing this:

```
switch control expression {
case pattern 1:
    statements
case pattern 2 where condition:
    statements
case pattern 3 where condition,
pattern 4 where condition:
    statements
default:
    statements
}
```

**Comment by Fred-J** [comment]
Another issue:
Swimat unfolded the code. I like to have all the methods folded and unfold the ones I need. But Swimat unfolds every thing upon usage and leaves it unfolded. 
It would be nice if the original folding is maintained.

**Comment by Jintin** [comment]
The switch case is solved in v1.3.4, please reinstall and reopen to see if it fit your need.
Thank you for reporting. ^^

I'm not very clear about the folding question.
Maybe is due to my poor English.
Could you give me some example?

And sure I'll tell you the progress.
^^

**Comment by Fred-J** [comment]
Do shift option command left arrow to fold all the codes, then shift option command the letter L lto do the indentation by Swimat, you should see the effect. 
It will be nice if the original folding is restored after you apply the indentation.

**Comment by Fred-J** [comment]
```
   if condition {
   |   do something
   |   more things
   |   if another condition {
   |   |   do more things
   |   |   and more
   |   }
   }
```

The above code Illustrates my previous post about the vertical line hint, which is used by most of the editors as a way of visual grouping

**Comment by Jintin** [comment]
Still don't get it, XCode doesn't provide the folding function, did you did that by 3rd plugin?
Or you wish me to do the function?

**Comment by Fred-J** [comment]
Go to Xcode > Preferences > Text Editing > and check 'Code folding ribbon'.

plus 3rd plugin as well.

**Comment by Jintin** [comment]
Thank you. I never notice such good feature.
But this might be a question how to avoid change the folding.
I'll try if I can control it.

**Comment by Fred-J** [comment]
I know you can do it keep going and I'm sure you will succeed

**Comment by Jintin** [comment]
Thanks for your faith on me,
I find out one solution, only replace the need format part.

1.3.6 version will search the diff from start and end.
If the folding part is out of the diff range, if will keep the folding format.

Please try and see if it fit your need. Thank you.

**Comment by Fred-J** [comment]
Good job.
Please note that swimat leaves 

```
//        yesBt.setTitle("Exit", forState: UIControlState.Normal)
```

but what is expected is

```
// yesBt.setTitle("Exit", forState: UIControlState.Normal)
```

**Comment by Fred-J** [comment]
remember also the swift is now an open source on linux, in case you need to look into the code to help in your plugin.

**Comment by Fred-J** [comment]
please note that swimat leaves

```
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {//called for each segue before viewDidLoad
```

but it would be nice if it one blank space is inserted between { and //

```
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) { //called for each segue before viewDidLoad
```

**Comment by Fred-J** [comment]
```
/*
   some code being commented 
      other code lines 
*/
```

better if swimat leave the indentation for the commented block above and not change it to 

```
/*
some code being commented 
other code lines 
*/
```

**Comment by Jintin** [comment]
About the comment block, there are many case is contradiction.
I need some time to figure out which is better.

For example, if change

``` swift
//        yesBt.setTitle("Exit", forState: UIControlState.Normal)
```

to

``` swift
// yesBt.setTitle("Exit", forState: UIControlState.Normal)
```

than it will imply

``` swift
//if condition {
//    do {
//        var a = 2
//    }
//}
```

to

``` swift
// if condition {
// do {
// var a = 2
// }
// }
```

**Comment by Fred-J** [comment]
Not necessarily, you can still Parse the text and  with  condition checking you can have the best of both worlds

**Comment by Fred-J** [comment]
after swimat:

```
        switch (type) {
        case "textField":
            result = UITextField(frame: CGRectMake(20, 100, 300, 40))
        case "segmented":
            let items = ["a", "b"]
            result = UISegmentedControl(items: items)
(result as? UISegmentedControl)?.selectedSegmentIndex = 0
        case "labels":
            result = UILabel(frame: CGRectMake(0, 0, 200, 21))
        case "checkBoxs": break
            // make a checkbox
        default:
            break
        }

```

expected:

```
        switch (type) {
        case "textField":
            result = UITextField(frame: CGRectMake(20, 100, 300, 40))
        case "segmented":
            let items = ["a", "b"]
            result = UISegmentedControl(items: items)
            (result as? UISegmentedControl)?.selectedSegmentIndex = 0
        case "labels":
            result = UILabel(frame: CGRectMake(0, 0, 200, 21))
        case "checkBoxs": break
            // make a checkbox
        default:
            break
        }

```

**Comment by Jintin** [comment]
please check 1.4.1.
It's a bug I made.
Thank you.

**Comment by Jintin** [comment]
code comment is not indent anymore in 1.4.2.
the key is if the comment // is the first char of the line.

``` swift
    func A() {
//      a = b + c
    }
```

**Comment by Jintin** [comment]
I think the only left is use in linux system.
But since it is written in objc now, it'll be a long run to achieve.
We'll change to pure swift project someday.
That time it'll be more easy to complete this function.
We'll close this issue now, if you face some other issue.
Please open a new one. Thank you for your contribute.
