### ISSUE TITLE
Do not format the content of comments?

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#70]
Swimat currently formats the content of comments by trimming leading space. In my experience, most of the times if the space is there, it's on purpose (for instance, code may be commented-out, or it may be a code sample), so I'd vote for Swimat leaving the content of comments alone.

**Comment by Jintin** [comment]
If code commented out by [cmd + /], it will remain the leading space.
You can try it.

``` swift
if a = 1 { // check a = 1
//  a = 2
}
```

**Comment by Jintin** [comment]
Do anyone watch this project has any other opinion?

**Comment by entonio** [comment]
I meant this, for instance:

```
                for (group, states) in casesByGroup {
                    uml += "frame \"\(group)\" {\n"
                    for state in states {
                        uml += "\t\(state)\n"
                    }
                    uml += "}\n"
                }
```

becomes

```
                /*
                 for (group, states) in casesByGroup {
                 uml += "frame \"\(group)\" {\n"
                 for state in states {
                 uml += "\t\(state)\n"
                 }
                 uml += "}\n"
                 }
                 */
```

**Comment by Jintin** [comment]
Can you use [cmd + /] to comment select line of code?
That way it will keep the place they were.

``` swift
//for (group, states) in casesByGroup {
//  uml += "frame \"\(group)\" {\n"
//  for state in states {
//      uml += "\t\(state)\n"
//  }
//  uml += "}\n"
//}
```

**Comment by Jintin** [comment]
If you don't have any further question, I'll close it a few days.
Thank you for your feedback.
