### ISSUE TITLE
Arithmetic in parenthesis can become strange (cast issue?)

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#71]
`(endDate - startDate).duration` becomes `(endDate -startDate).duration`

For context, when I do `(endDate - startDate)` it casts to `NSDateComponents`. Not that it should matter unless you can somehow detect a cast.

**Comment by Jintin** [comment]
I didn't see any problem in my environment.
Would you like to update to test if it fix in latest version.
Thank you.

``` swift
(endDate - startDate).duration
```

**Comment by Jintin** [comment]
I'll close it now, reopen it if it not working. ^^
