### ISSUE TITLE
Ternary operator broken if there is another operator in it

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#72]
`let foo = (true) ? 2 % 1 : 3`
`let foo = (true) ? 2 + 1 : 3`

becomes

`let foo = (true) ? 2 % 1: 3`
`let foo = (true) ? 2 + 1: 3`

**Comment by Jintin** [comment]
There is an enhancement need implement about this case.
For now, you can add () to group the calculation.
Like this:

``` swift
let foo = (true) ? (2 % 1) : 3
let foo = (true) ? (2 + 1) : 3
```

We'll keep doing the job to make this more intelligent.
Thank you for your feedback.

**Comment by Jintin** [comment]
Do you think it's acceptable now, I'll do the swift version with more general solution about this.

**Comment by saagarjha** [comment]
I'm having an still having an issue with this, in particular, with a negative sign in the ternary operator. This:

```
let foo = nil ?? -1
```

becomes this:

```
let foo = nil ?? - 1
```

This fails to compile as well as being undesired behavior. I'm using the extension branch, by the way.

**Comment by Jintin** [comment]
Please update and try again.
Congrats you can use extension version.

**Comment by saagarjha** [comment]
Works great, thanks!

**Comment by Jintin** [comment]
Please try v1.3 again, thank you for your feedback.
