### ISSUE TITLE
run Swiftmat from CLI

### ISSUE THREAD

**Issue by zielinskikamil** [Jintin/Swimat#75]
Hey, 
First of all, I would like to thank you for this tool. It's really cool!

Do you know it there is any way of run formatting from a command line?
eg.
I would like to use this tool to format all files in a project directory.

Regards,
Kamil

**Comment by Jintin** [comment]
Yes, we are going to transfer the code to swift.
When everything is done, you can execute it from terminal.
It may take a few month, but we'll definitely do this.
Thank you for your feedback.

**Comment by saagarjha** [comment]
@Jintin Has any work been done on this (or I could take a look at it)? I'd like to use it to run Swimat when a build starts, since you can add a shell command to run as a Behavior.

**Comment by Jintin** [comment]
Sure, you can try it.

**Comment by saagarjha** [comment]
Check out #130.

**Comment by Jintin** [comment]
Since @saagarjha help the CLI part.
This issue will be closed.
Thanks everyone.
