### ISSUE TITLE
I can’t say this for English, so see the picture.

### ISSUE THREAD

**Issue by thoamsy** [Jintin/Swimat#8]
![Uploading 屏幕快照 2015-12-07 12.23.07.png…]()
![2015-12-07 12 23 20](https://cloud.githubusercontent.com/assets/11444431/11619017/95ca55b6-9cdd-11e5-8018-6097f554619c.png)

Obviously, the ) and the symbol after it will be separate by a space character,
but in this case, it’s not well.

**Comment by Jintin** [comment]
Thank you for report.
I'm ok in Chinese if you does.
Please reinstall, reopen and try v1.3.2.
If the problem solve, please let me know to close it. ^^

**Comment by thoamsy** [comment]
Good, the bug has been solved. But this is a new bug.
Before
![2015-12-07 21 45 26](https://cloud.githubusercontent.com/assets/11444431/11647723/9b5e533c-9da6-11e5-9d06-142ecfc36fd7.png)
After
![2015-12-07 21 45 12](https://cloud.githubusercontent.com/assets/11444431/11647725/9e354c8c-9da6-11e5-9e80-5348a4f7df8b.png)

**Comment by Jintin** [comment]
It's the same bug as listed.
A regex error.
Solved in v1.3.4, please reinstall and reopen to see if it fit your need.
Thank you for reporting. ^^

**Comment by thoamsy** [comment]
Yeah, perfect. If you can speak Chinese that I believe I can feedback more.

**Comment by Jintin** [comment]
It's always welcome.
歡迎提出任何建議讓Swimat變得更好用

**Comment by QueenYoung** [comment]
原来是台湾朋友啊？希望可以先添加部分格式转换功能。这样即使有些 Bug 的话，也不会显得那么令人抓头皮了。

**Comment by thoamsy** [comment]
原来是台湾朋友啊？希望可以先添加选择部分代码的格式转换功能。这样即使有些 Bug 的话，也不会显得那么令人抓头皮了。

**Comment by Jintin** [comment]
好的 這個建議非常的好
給我一些時間我會完成它

Thank you for your opinion, I'll do this feature in later version.

**Comment by Jintin** [comment]
你好
抱歉拖了一些時間
部分格式化程式的功能已經完成
可以重新安裝看看
有問題再跟我說 謝謝

The range format function is done in 1.4, please try and see if it fix your need.
Thank you.

**Comment by thoamsy** [comment]
这段时间，因为一些其他的事情，我可能 Swift 用得少
可能不能及时体验，可能会过一段时间才有积极的反馈。
不过感谢你的辛勤和无私😊
