### ISSUE TITLE
Function arguments formatting

### ISSUE THREAD

**Issue by dejanskledar** [Jintin/Swimat#82]
Are there any plans in the future to support the formating for the function arguments?

Also maybe for dictionaries, arrays, long function call etc,,. Like the clang formatter for Obj-C?

**Comment by Jintin** [comment]
I'm not really know about function arguments, could you give me more example?
Thank you for your feedback.

**Comment by dejanskledar** [comment]
Sorry for the long response.

Here's what I mean:

![image](https://cloud.githubusercontent.com/assets/13760486/14307654/17806b5c-fbd1-11e5-944b-a3cec74dccec.png)

Do you see how the parameters are aligned? Its really better and its easier to read the code than in the current Swift way (all inline).

Another example for an array:

![image](https://cloud.githubusercontent.com/assets/13760486/14307595/c10d24fe-fbd0-11e5-93a3-c6f40b72ff19.png)

For Objective C this handles the Clang format. You can check it out here: https://github.com/travisjeffery/ClangFormat-Xcode

**Comment by luisrecuenco** [comment]
Hi @Jintin.

First off, congrats for this great tool. I just discovered it and it's improved my workflow a lot. I only have a minor complaint about indentation.

This is how Xcode indents the method below (Structure -> Re-indent)

```
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
                          mediaRouter: mediaRouter(),
                          discoverRouter: discoverRouter(),
                          profileRouter: profileRouter()
        )
    }
```

And this is how Swimat indents it:

```
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
            mediaRouter: mediaRouter(),
            discoverRouter: discoverRouter(),
            profileRouter: profileRouter()
        )
    }
```

Any plans on fixing this issue?

Thanks

**Comment by Jintin** [comment]
Thank you for your feedback @luisrecuenco .
It's kind of complicate but possible.
After working on pure swift version we will provide several custom setting like this one.

**Comment by Jintin** [comment]
Would you please try our swift version?
I've add this feature today.
https://github.com/Jintin/Swimat/tree/swift
Clone, build and restart Xcode.
If you encounter any problem, please feel free to let me know.
Thank you.

**Comment by luisrecuenco** [comment]
Hi Jintin,

Thanks for the fix. Unfortunately, it's still not working. This is how the code looks like now:

```
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
        mediaRouter: mediaRouter(),
        discoverRouter: discoverRouter(),
        profileRouter: profileRouter())
    }
```

**Comment by Jintin** [comment]
Sorry, it's my mistake.
Can you update and try again.
it should looks like:

``` swift
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
                          mediaRouter: mediaRouter(),
                          discoverRouter: discoverRouter(),
                          profileRouter: profileRouter())
    }
```

**Comment by luisrecuenco** [comment]
Still not working...

```
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
                                mediaRouter: mediaRouter(),
                                discoverRouter: discoverRouter(),
                                profileRouter: profileRouter())
    }
```

**Comment by Jintin** [comment]
Not sure what going on.
Here is the outcome in my computer, you can run to start a new XCode app for testing after update.

``` swift
    func mainRouter() -> MainRouter {
        return MainRouter(homeRouter: homeRouter(),
                          mediaRouter: mediaRouter(),
                          discoverRouter: discoverRouter(),
                          profileRouter: profileRouter())
    }
```

**Comment by Jintin** [comment]
Maybe you can change the name in Swimat.swift to see if your update is correct.

``` swift
class Swimat: NSObject {

    let name = "Swimat2" // for test
```

**Comment by luisrecuenco** [comment]
Yep, my update is correct, but still not working, sorry... Thanks for the help though

**Comment by Jintin** [comment]
@luisrecuenco Could you try the `extension` branch on xcode8?

**Comment by Jintin** [comment]
@luisrecuenco It been a while so I'll close this issue now.
If you have any further question or problem, feel free to create a new issue.
