### ISSUE TITLE
guard let multiline indentation

### ISSUE THREAD

**Issue by esetnik** [Jintin/Swimat#83]
When using guard let with multiple declarations on newlines the first declaration is not indented

actual:

```
        guard let
        typeString = representation.valueForKeyPath("type") as? String,
            type = FeatureKind(rawValue: typeString)
        else {
            return nil
        }
```

expected:

```
        guard let
            typeString = representation.valueForKeyPath("type") as? String,
            type = FeatureKind(rawValue: typeString)
        else {
            return nil
        }
```

**Comment by Jintin** [comment]
Since we don't parse the syntax, it will be a little hard to detect when to indent.
Could you put the first line together?
We'll make some change in our swift version of Swimat.
Thank you for your feedback.
You may see the similar  issue in here. #55

``` swift
        guard let typeString = representation.valueForKeyPath("type") as? String,
            type = FeatureKind(rawValue: typeString)
        else {
            return nil
        }
```

**Comment by esetnik** [comment]
Yeah I can do that. It's not as clean though and triggers line length warnings in more cases. Let me know if I can help with the grammar parser work.

**Comment by Jintin** [comment]
Thank you.
I'll close the issue for now.
If you want to implement the function.
Please take a look at `NSString+Common.m` with the following function.
`-(bool) isCompleteLine:(NSUInteger) index curBlock:(NSString *) curBlock`
