### ISSUE TITLE
Do not format shebang

### ISSUE THREAD

**Issue by entonio** [Jintin/Swimat#84]
Swift command-line scripts usually have a shebang in their first line.
Swimat currently turns 

```
#!/usr/bin/xcrun --sdk macosx swift
```

  or

```
#!/usr/bin/swift
```

into

```
#! / usr / bin / xcrun --sdk macosx swift
```

  or

```
#! / usr / bin / swift
```

which breaks the script.

**Comment by Jintin** [comment]
Thank you for your feedback, please update and try again.
