### ISSUE TITLE
Sub-listing in comments

### ISSUE THREAD

**Issue by RMPtc** [Jintin/Swimat#85]
Expected:

```
/// Method foo without any use
///
/// ---
///
/// - parameters:
///     - parameter1: Foo parameter without any use.
///     - parameter2: Another foo parameter without any use.
func foo(parameter1:Foo, parameter2:Foo){}

```

Result after formating

```
/// Method foo without any use
///
/// ---
///
/// - parameters:
/// - parameter1: Foo parameter without any use.
/// - parameter2: Another foo parameter without any use.
func foo(parameter1:Foo, parameter2:Foo){}
```

This is braking the documentation by removing the sub-listing when listing the method parameters on the documentation.

**Comment by Jintin** [comment]
I didn't notice that, thank you for your feedback.
Please reinstall and try again. ^^

**Comment by RMPtc** [comment]
I removed it and also removed Alcatraz and reinstalled everything again and it still does that. Xcode 7.3 and Swift 2.2

**Comment by Jintin** [comment]
Maybe need reopen Xcode.
