### ISSUE TITLE
Dont split operators from Argo

### ISSUE THREAD

**Issue by pteasima** [Jintin/Swimat#87]
If there's no way to fix formatting of all allowed swift operators, please fix at least these cases:

https://github.com/thoughtbot/Argo/blob/255196cabc3d84477ba9cd7677c16443cf87775c/Argo/Operators/Argo.swift
https://github.com/thoughtbot/Argo/blob/255196cabc3d84477ba9cd7677c16443cf87775c/Argo/Types/Decoded/Alternative.swift
https://github.com/thoughtbot/Runes/blob/master/Source/Runes.swift

Thanks

**Comment by Jintin** [comment]
Thank you for your info.
Please reinstall and try again.
