### ISSUE TITLE
empty space when formatting with selection

### ISSUE THREAD

**Issue by pteasima** [Jintin/Swimat#90]
when I select a word (or multiple words) so that the selection starts at the beginning of a word, then I press format,  the word gets further indented. There seem to be multiple cases:
1. the word starts at the beginning of the line - no problem here.
2. the word is indented (var, func, init, ..) - the word gets indented several spaces more
3. the word starts 1 or multiple spaces after another word (variable name, 'var' in 'weak var',...) - the word gets indented one space more.

**Comment by Jintin** [comment]
Yes, thanks for your feedback, please reinstall and try again.
