### ISSUE TITLE
Unary operator separated from operand in variadic for loop

### ISSUE THREAD

**Issue by bdrelling** [Jintin/Swimat#97]
Example:

<img width="759" alt="screen shot 2016-04-18 at 9 06 16 pm" src="https://cloud.githubusercontent.com/assets/3022693/14624531/8930bc2a-05a9-11e6-9ecf-1358ae2da20a.png">

**Comment by bdrelling** [comment]
Workaround also gets collapsed weird:

<img width="147" alt="screen shot 2016-04-18 at 9 07 43 pm" src="https://cloud.githubusercontent.com/assets/3022693/14624536/9c96acd4-05a9-11e6-970d-12581034f834.png">

**Comment by Jintin** [comment]
Both case work now.
Thank you for report it. ^^
