### ISSUE TITLE
Problems with Operator

### ISSUE THREAD

**Issue by RafaelPlantard** [Jintin/Swimat#98]
A infix operator from [Observable-Swift](https://github.com/yeahdongcn/UIColor-Hex-Swift) pod:

Correct mode:

``` swift
if isGreenMode^ {
    tintColor = backgroundColor
    backgroundColor = UIColor.whiteColor()
}
```

Current mode:

``` swift
if isGreenMode ^ {
    tintColor = backgroundColor
    backgroundColor = UIColor.whiteColor()
}
```

**Comment by Jintin** [comment]
Thank you for your feedback, please reinstall and try again.

**Comment by RafaelPlantard** [comment]
Hi, the same problem in other context:

**expected**:

``` swift
let secretKey = credentialsProvider^.secretKey
```

**today**:

``` swift
let secretKey = credentialsProvider^ .secretKey
```

**Comment by Jintin** [comment]
Is `^` a custom operator?

**Comment by RafaelPlantard** [comment]
No, it's a operator fro Observable Swift pod.

**Comment by Jintin** [comment]
It should fix now, you can reinstall and try again.

**Comment by RafaelPlantard** [comment]
Thanks again @Jintin
