### ISSUE TITLE
Newline after opening brace

### ISSUE THREAD

**Issue by krummler** [Jintin/Swimat#99]
Thanks for this plugin, it really helps our team!

Would it be possible to add an option to force a newline after an opening brace? Or is it possible to alter this somewhere manually?

```
class SomeClass: NSObject {
    var someVariable:[NSObject]

    func doSomething() {
        if let something = someVariable.first as? SomeClass {
            NSLog("")
        }
    }
}
```

would become

```
class SomeClass: NSObject {

    var someVariable:[NSObject]

    func doSomething() {

        if let something = someVariable.first as? SomeClass {

            NSLog("")
        }
    }
}
```

**Comment by iwasrobbed** [comment]
I was looking for something similar, but only for open brace of class / extension / struct (e.g. not for funcs)

**Comment by Jintin** [comment]
Yes, it is very helpful function, we'll do it.
Thank you for great opinion.

**Comment by Jintin** [comment]
In current version, Swimat will not remove newline only if you add newline twice.
So if you manually add newline it will keep. 
And the future version, will add more rule like tailor suggestion, as @iwasrobbed said, open brace of class / extension / struc.
Thank you for all yours feedback to let Swimat a better tool.
We'll keep move on. ^^
